/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
)

// checks if the AlertItemV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlertItemV1{}

// AlertItemV1 A single alert returned by the upstream Recommend service.
type AlertItemV1 struct {
	// Human-readable name of the dataset or index that triggered the alert.
	Name *string `json:"name,omitempty"`
	// Related news articles driving this alert.
	News []NewsItemV1 `json:"news,omitempty"`
	// Percentage change that triggered the alert (negative = decline, positive = surge).
	PctChange *float64 `json:"pct_change,omitempty"`
	// Whether this alert is currently trending across the platform.
	Trending *bool `json:"trending,omitempty"`
}

// NewAlertItemV1 instantiates a new AlertItemV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertItemV1() *AlertItemV1 {
	this := AlertItemV1{}
	return &this
}

// NewAlertItemV1WithDefaults instantiates a new AlertItemV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertItemV1WithDefaults() *AlertItemV1 {
	this := AlertItemV1{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AlertItemV1) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertItemV1) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AlertItemV1) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AlertItemV1) SetName(v string) {
	o.Name = &v
}

// GetNews returns the News field value if set, zero value otherwise.
func (o *AlertItemV1) GetNews() []NewsItemV1 {
	if o == nil || IsNil(o.News) {
		var ret []NewsItemV1
		return ret
	}
	return o.News
}

// GetNewsOk returns a tuple with the News field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertItemV1) GetNewsOk() ([]NewsItemV1, bool) {
	if o == nil || IsNil(o.News) {
		return nil, false
	}
	return o.News, true
}

// HasNews returns a boolean if a field has been set.
func (o *AlertItemV1) HasNews() bool {
	if o != nil && !IsNil(o.News) {
		return true
	}

	return false
}

// SetNews gets a reference to the given []NewsItemV1 and assigns it to the News field.
func (o *AlertItemV1) SetNews(v []NewsItemV1) {
	o.News = v
}

// GetPctChange returns the PctChange field value if set, zero value otherwise.
func (o *AlertItemV1) GetPctChange() float64 {
	if o == nil || IsNil(o.PctChange) {
		var ret float64
		return ret
	}
	return *o.PctChange
}

// GetPctChangeOk returns a tuple with the PctChange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertItemV1) GetPctChangeOk() (*float64, bool) {
	if o == nil || IsNil(o.PctChange) {
		return nil, false
	}
	return o.PctChange, true
}

// HasPctChange returns a boolean if a field has been set.
func (o *AlertItemV1) HasPctChange() bool {
	if o != nil && !IsNil(o.PctChange) {
		return true
	}

	return false
}

// SetPctChange gets a reference to the given float64 and assigns it to the PctChange field.
func (o *AlertItemV1) SetPctChange(v float64) {
	o.PctChange = &v
}

// GetTrending returns the Trending field value if set, zero value otherwise.
func (o *AlertItemV1) GetTrending() bool {
	if o == nil || IsNil(o.Trending) {
		var ret bool
		return ret
	}
	return *o.Trending
}

// GetTrendingOk returns a tuple with the Trending field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertItemV1) GetTrendingOk() (*bool, bool) {
	if o == nil || IsNil(o.Trending) {
		return nil, false
	}
	return o.Trending, true
}

// HasTrending returns a boolean if a field has been set.
func (o *AlertItemV1) HasTrending() bool {
	if o != nil && !IsNil(o.Trending) {
		return true
	}

	return false
}

// SetTrending gets a reference to the given bool and assigns it to the Trending field.
func (o *AlertItemV1) SetTrending(v bool) {
	o.Trending = &v
}

func (o AlertItemV1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlertItemV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.News) {
		toSerialize["news"] = o.News
	}
	if !IsNil(o.PctChange) {
		toSerialize["pct_change"] = o.PctChange
	}
	if !IsNil(o.Trending) {
		toSerialize["trending"] = o.Trending
	}
	return toSerialize, nil
}

type NullableAlertItemV1 struct {
	value *AlertItemV1
	isSet bool
}

func (v NullableAlertItemV1) Get() *AlertItemV1 {
	return v.value
}

func (v *NullableAlertItemV1) Set(val *AlertItemV1) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertItemV1) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertItemV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertItemV1(val *AlertItemV1) *NullableAlertItemV1 {
	return &NullableAlertItemV1{value: val, isSet: true}
}

func (v NullableAlertItemV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertItemV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


