/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
)

// checks if the ForecastArtifactMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ForecastArtifactMeta{}

// ForecastArtifactMeta Metadata for a single output file produced by a completed forecast job.
type ForecastArtifactMeta struct {
	// MIME type of the artifact (e.g. `application/json`).
	ContentType *string `json:"content_type,omitempty"`
	// Relative URL to stream via `GET /api/v1/forecasts/{id}/artifacts/{name}`.
	Href *string `json:"href,omitempty"`
	// Artifact filename (e.g. `forecast.json`, `backtest_metrics.json`).
	Name *string `json:"name,omitempty"`
	// File size in bytes.
	Size *int64 `json:"size,omitempty"`
}

// NewForecastArtifactMeta instantiates a new ForecastArtifactMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForecastArtifactMeta() *ForecastArtifactMeta {
	this := ForecastArtifactMeta{}
	return &this
}

// NewForecastArtifactMetaWithDefaults instantiates a new ForecastArtifactMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForecastArtifactMetaWithDefaults() *ForecastArtifactMeta {
	this := ForecastArtifactMeta{}
	return &this
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *ForecastArtifactMeta) GetContentType() string {
	if o == nil || IsNil(o.ContentType) {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastArtifactMeta) GetContentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ContentType) {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *ForecastArtifactMeta) HasContentType() bool {
	if o != nil && !IsNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *ForecastArtifactMeta) SetContentType(v string) {
	o.ContentType = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ForecastArtifactMeta) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastArtifactMeta) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ForecastArtifactMeta) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ForecastArtifactMeta) SetHref(v string) {
	o.Href = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ForecastArtifactMeta) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastArtifactMeta) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ForecastArtifactMeta) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ForecastArtifactMeta) SetName(v string) {
	o.Name = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *ForecastArtifactMeta) GetSize() int64 {
	if o == nil || IsNil(o.Size) {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastArtifactMeta) GetSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *ForecastArtifactMeta) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *ForecastArtifactMeta) SetSize(v int64) {
	o.Size = &v
}

func (o ForecastArtifactMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ForecastArtifactMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContentType) {
		toSerialize["content_type"] = o.ContentType
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	return toSerialize, nil
}

type NullableForecastArtifactMeta struct {
	value *ForecastArtifactMeta
	isSet bool
}

func (v NullableForecastArtifactMeta) Get() *ForecastArtifactMeta {
	return v.value
}

func (v *NullableForecastArtifactMeta) Set(val *ForecastArtifactMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableForecastArtifactMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableForecastArtifactMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForecastArtifactMeta(val *ForecastArtifactMeta) *NullableForecastArtifactMeta {
	return &NullableForecastArtifactMeta{value: val, isSet: true}
}

func (v NullableForecastArtifactMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForecastArtifactMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


