/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the JobSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobSummary{}

// JobSummary Lightweight summary of an async job (no payload or artifact manifest).
type JobSummary struct {
	CreatedAt time.Time `json:"created_at"`
	// Final settled charge for the job in EUR cents. Null until the job reaches a terminal state.
	EurCentsFinal NullableInt64 `json:"eur_cents_final,omitempty"`
	JobId string `json:"job_id"`
	// Pipeline that produced this job — currently always `forecast`.
	PipelineType string `json:"pipeline_type"`
	// Opaque internal run identifier. Omitted for jobs that have not started yet; include in support requests.
	RunId *string `json:"run_id,omitempty"`
	// True once the job has reached a terminal state and the charge has been posted.
	Settled bool `json:"settled"`
	SettledAt NullableTime `json:"settled_at,omitempty"`
	Status string `json:"status"`
	// Human-readable failure message for `failed` or `canceled` jobs; null for non-terminal statuses or cleanly-canceled jobs.
	TerminalReason NullableString `json:"terminal_reason,omitempty"`
	// Opaque internal workflow identifier. Omitted for jobs that have not started yet; include in support requests.
	WorkflowId *string `json:"workflow_id,omitempty"`
}

type _JobSummary JobSummary

// NewJobSummary instantiates a new JobSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobSummary(createdAt time.Time, jobId string, pipelineType string, settled bool, status string) *JobSummary {
	this := JobSummary{}
	this.CreatedAt = createdAt
	this.JobId = jobId
	this.PipelineType = pipelineType
	this.Settled = settled
	this.Status = status
	return &this
}

// NewJobSummaryWithDefaults instantiates a new JobSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobSummaryWithDefaults() *JobSummary {
	this := JobSummary{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *JobSummary) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *JobSummary) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *JobSummary) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetEurCentsFinal returns the EurCentsFinal field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobSummary) GetEurCentsFinal() int64 {
	if o == nil || IsNil(o.EurCentsFinal.Get()) {
		var ret int64
		return ret
	}
	return *o.EurCentsFinal.Get()
}

// GetEurCentsFinalOk returns a tuple with the EurCentsFinal field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobSummary) GetEurCentsFinalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.EurCentsFinal.Get(), o.EurCentsFinal.IsSet()
}

// HasEurCentsFinal returns a boolean if a field has been set.
func (o *JobSummary) HasEurCentsFinal() bool {
	if o != nil && o.EurCentsFinal.IsSet() {
		return true
	}

	return false
}

// SetEurCentsFinal gets a reference to the given NullableInt64 and assigns it to the EurCentsFinal field.
func (o *JobSummary) SetEurCentsFinal(v int64) {
	o.EurCentsFinal.Set(&v)
}
// SetEurCentsFinalNil sets the value for EurCentsFinal to be an explicit nil
func (o *JobSummary) SetEurCentsFinalNil() {
	o.EurCentsFinal.Set(nil)
}

// UnsetEurCentsFinal ensures that no value is present for EurCentsFinal, not even an explicit nil
func (o *JobSummary) UnsetEurCentsFinal() {
	o.EurCentsFinal.Unset()
}

// GetJobId returns the JobId field value
func (o *JobSummary) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *JobSummary) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *JobSummary) SetJobId(v string) {
	o.JobId = v
}

// GetPipelineType returns the PipelineType field value
func (o *JobSummary) GetPipelineType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PipelineType
}

// GetPipelineTypeOk returns a tuple with the PipelineType field value
// and a boolean to check if the value has been set.
func (o *JobSummary) GetPipelineTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PipelineType, true
}

// SetPipelineType sets field value
func (o *JobSummary) SetPipelineType(v string) {
	o.PipelineType = v
}

// GetRunId returns the RunId field value if set, zero value otherwise.
func (o *JobSummary) GetRunId() string {
	if o == nil || IsNil(o.RunId) {
		var ret string
		return ret
	}
	return *o.RunId
}

// GetRunIdOk returns a tuple with the RunId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobSummary) GetRunIdOk() (*string, bool) {
	if o == nil || IsNil(o.RunId) {
		return nil, false
	}
	return o.RunId, true
}

// HasRunId returns a boolean if a field has been set.
func (o *JobSummary) HasRunId() bool {
	if o != nil && !IsNil(o.RunId) {
		return true
	}

	return false
}

// SetRunId gets a reference to the given string and assigns it to the RunId field.
func (o *JobSummary) SetRunId(v string) {
	o.RunId = &v
}

// GetSettled returns the Settled field value
func (o *JobSummary) GetSettled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Settled
}

// GetSettledOk returns a tuple with the Settled field value
// and a boolean to check if the value has been set.
func (o *JobSummary) GetSettledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Settled, true
}

// SetSettled sets field value
func (o *JobSummary) SetSettled(v bool) {
	o.Settled = v
}

// GetSettledAt returns the SettledAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobSummary) GetSettledAt() time.Time {
	if o == nil || IsNil(o.SettledAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.SettledAt.Get()
}

// GetSettledAtOk returns a tuple with the SettledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobSummary) GetSettledAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.SettledAt.Get(), o.SettledAt.IsSet()
}

// HasSettledAt returns a boolean if a field has been set.
func (o *JobSummary) HasSettledAt() bool {
	if o != nil && o.SettledAt.IsSet() {
		return true
	}

	return false
}

// SetSettledAt gets a reference to the given NullableTime and assigns it to the SettledAt field.
func (o *JobSummary) SetSettledAt(v time.Time) {
	o.SettledAt.Set(&v)
}
// SetSettledAtNil sets the value for SettledAt to be an explicit nil
func (o *JobSummary) SetSettledAtNil() {
	o.SettledAt.Set(nil)
}

// UnsetSettledAt ensures that no value is present for SettledAt, not even an explicit nil
func (o *JobSummary) UnsetSettledAt() {
	o.SettledAt.Unset()
}

// GetStatus returns the Status field value
func (o *JobSummary) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *JobSummary) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *JobSummary) SetStatus(v string) {
	o.Status = v
}

// GetTerminalReason returns the TerminalReason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobSummary) GetTerminalReason() string {
	if o == nil || IsNil(o.TerminalReason.Get()) {
		var ret string
		return ret
	}
	return *o.TerminalReason.Get()
}

// GetTerminalReasonOk returns a tuple with the TerminalReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobSummary) GetTerminalReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TerminalReason.Get(), o.TerminalReason.IsSet()
}

// HasTerminalReason returns a boolean if a field has been set.
func (o *JobSummary) HasTerminalReason() bool {
	if o != nil && o.TerminalReason.IsSet() {
		return true
	}

	return false
}

// SetTerminalReason gets a reference to the given NullableString and assigns it to the TerminalReason field.
func (o *JobSummary) SetTerminalReason(v string) {
	o.TerminalReason.Set(&v)
}
// SetTerminalReasonNil sets the value for TerminalReason to be an explicit nil
func (o *JobSummary) SetTerminalReasonNil() {
	o.TerminalReason.Set(nil)
}

// UnsetTerminalReason ensures that no value is present for TerminalReason, not even an explicit nil
func (o *JobSummary) UnsetTerminalReason() {
	o.TerminalReason.Unset()
}

// GetWorkflowId returns the WorkflowId field value if set, zero value otherwise.
func (o *JobSummary) GetWorkflowId() string {
	if o == nil || IsNil(o.WorkflowId) {
		var ret string
		return ret
	}
	return *o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobSummary) GetWorkflowIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorkflowId) {
		return nil, false
	}
	return o.WorkflowId, true
}

// HasWorkflowId returns a boolean if a field has been set.
func (o *JobSummary) HasWorkflowId() bool {
	if o != nil && !IsNil(o.WorkflowId) {
		return true
	}

	return false
}

// SetWorkflowId gets a reference to the given string and assigns it to the WorkflowId field.
func (o *JobSummary) SetWorkflowId(v string) {
	o.WorkflowId = &v
}

func (o JobSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created_at"] = o.CreatedAt
	if o.EurCentsFinal.IsSet() {
		toSerialize["eur_cents_final"] = o.EurCentsFinal.Get()
	}
	toSerialize["job_id"] = o.JobId
	toSerialize["pipeline_type"] = o.PipelineType
	if !IsNil(o.RunId) {
		toSerialize["run_id"] = o.RunId
	}
	toSerialize["settled"] = o.Settled
	if o.SettledAt.IsSet() {
		toSerialize["settled_at"] = o.SettledAt.Get()
	}
	toSerialize["status"] = o.Status
	if o.TerminalReason.IsSet() {
		toSerialize["terminal_reason"] = o.TerminalReason.Get()
	}
	if !IsNil(o.WorkflowId) {
		toSerialize["workflow_id"] = o.WorkflowId
	}
	return toSerialize, nil
}

func (o *JobSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"job_id",
		"pipeline_type",
		"settled",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobSummary := _JobSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobSummary)

	if err != nil {
		return err
	}

	*o = JobSummary(varJobSummary)

	return err
}

type NullableJobSummary struct {
	value *JobSummary
	isSet bool
}

func (v NullableJobSummary) Get() *JobSummary {
	return v.value
}

func (v *NullableJobSummary) Set(val *JobSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableJobSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableJobSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobSummary(val *JobSummary) *NullableJobSummary {
	return &NullableJobSummary{value: val, isSet: true}
}

func (v NullableJobSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


