/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AutoRechargeState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AutoRechargeState{}

// AutoRechargeState struct for AutoRechargeState
type AutoRechargeState struct {
	// When the available balance drops below this many EUR cents, a recharge is triggered.
	BelowEurCents int64 `json:"below_eur_cents"`
	// Whether auto-recharge is active for this account.
	Enabled bool `json:"enabled"`
	// Whether a Stripe customer record exists (required for auto-recharge to run).
	HasStripeCustomer bool `json:"has_stripe_customer"`
	// EUR cents charged via auto-recharge in the current UTC calendar month.
	MeterCents int64 `json:"meter_cents"`
	// UTC month start for `meter_cents`; null if no auto-recharge has run this month.
	MeterMonth NullableString `json:"meter_month,omitempty"`
	// Maximum EUR cents that may be charged via auto-recharge per UTC calendar month. 0 = no cap.
	MonthlyCapCents int64 `json:"monthly_cap_cents"`
	// Balance target after a successful recharge, in EUR cents.
	TargetEurCents int64 `json:"target_eur_cents"`
}

type _AutoRechargeState AutoRechargeState

// NewAutoRechargeState instantiates a new AutoRechargeState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAutoRechargeState(belowEurCents int64, enabled bool, hasStripeCustomer bool, meterCents int64, monthlyCapCents int64, targetEurCents int64) *AutoRechargeState {
	this := AutoRechargeState{}
	this.BelowEurCents = belowEurCents
	this.Enabled = enabled
	this.HasStripeCustomer = hasStripeCustomer
	this.MeterCents = meterCents
	this.MonthlyCapCents = monthlyCapCents
	this.TargetEurCents = targetEurCents
	return &this
}

// NewAutoRechargeStateWithDefaults instantiates a new AutoRechargeState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAutoRechargeStateWithDefaults() *AutoRechargeState {
	this := AutoRechargeState{}
	return &this
}

// GetBelowEurCents returns the BelowEurCents field value
func (o *AutoRechargeState) GetBelowEurCents() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.BelowEurCents
}

// GetBelowEurCentsOk returns a tuple with the BelowEurCents field value
// and a boolean to check if the value has been set.
func (o *AutoRechargeState) GetBelowEurCentsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BelowEurCents, true
}

// SetBelowEurCents sets field value
func (o *AutoRechargeState) SetBelowEurCents(v int64) {
	o.BelowEurCents = v
}

// GetEnabled returns the Enabled field value
func (o *AutoRechargeState) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *AutoRechargeState) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *AutoRechargeState) SetEnabled(v bool) {
	o.Enabled = v
}

// GetHasStripeCustomer returns the HasStripeCustomer field value
func (o *AutoRechargeState) GetHasStripeCustomer() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasStripeCustomer
}

// GetHasStripeCustomerOk returns a tuple with the HasStripeCustomer field value
// and a boolean to check if the value has been set.
func (o *AutoRechargeState) GetHasStripeCustomerOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasStripeCustomer, true
}

// SetHasStripeCustomer sets field value
func (o *AutoRechargeState) SetHasStripeCustomer(v bool) {
	o.HasStripeCustomer = v
}

// GetMeterCents returns the MeterCents field value
func (o *AutoRechargeState) GetMeterCents() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MeterCents
}

// GetMeterCentsOk returns a tuple with the MeterCents field value
// and a boolean to check if the value has been set.
func (o *AutoRechargeState) GetMeterCentsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MeterCents, true
}

// SetMeterCents sets field value
func (o *AutoRechargeState) SetMeterCents(v int64) {
	o.MeterCents = v
}

// GetMeterMonth returns the MeterMonth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AutoRechargeState) GetMeterMonth() string {
	if o == nil || IsNil(o.MeterMonth.Get()) {
		var ret string
		return ret
	}
	return *o.MeterMonth.Get()
}

// GetMeterMonthOk returns a tuple with the MeterMonth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AutoRechargeState) GetMeterMonthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MeterMonth.Get(), o.MeterMonth.IsSet()
}

// HasMeterMonth returns a boolean if a field has been set.
func (o *AutoRechargeState) HasMeterMonth() bool {
	if o != nil && o.MeterMonth.IsSet() {
		return true
	}

	return false
}

// SetMeterMonth gets a reference to the given NullableString and assigns it to the MeterMonth field.
func (o *AutoRechargeState) SetMeterMonth(v string) {
	o.MeterMonth.Set(&v)
}
// SetMeterMonthNil sets the value for MeterMonth to be an explicit nil
func (o *AutoRechargeState) SetMeterMonthNil() {
	o.MeterMonth.Set(nil)
}

// UnsetMeterMonth ensures that no value is present for MeterMonth, not even an explicit nil
func (o *AutoRechargeState) UnsetMeterMonth() {
	o.MeterMonth.Unset()
}

// GetMonthlyCapCents returns the MonthlyCapCents field value
func (o *AutoRechargeState) GetMonthlyCapCents() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MonthlyCapCents
}

// GetMonthlyCapCentsOk returns a tuple with the MonthlyCapCents field value
// and a boolean to check if the value has been set.
func (o *AutoRechargeState) GetMonthlyCapCentsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MonthlyCapCents, true
}

// SetMonthlyCapCents sets field value
func (o *AutoRechargeState) SetMonthlyCapCents(v int64) {
	o.MonthlyCapCents = v
}

// GetTargetEurCents returns the TargetEurCents field value
func (o *AutoRechargeState) GetTargetEurCents() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TargetEurCents
}

// GetTargetEurCentsOk returns a tuple with the TargetEurCents field value
// and a boolean to check if the value has been set.
func (o *AutoRechargeState) GetTargetEurCentsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetEurCents, true
}

// SetTargetEurCents sets field value
func (o *AutoRechargeState) SetTargetEurCents(v int64) {
	o.TargetEurCents = v
}

func (o AutoRechargeState) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AutoRechargeState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["below_eur_cents"] = o.BelowEurCents
	toSerialize["enabled"] = o.Enabled
	toSerialize["has_stripe_customer"] = o.HasStripeCustomer
	toSerialize["meter_cents"] = o.MeterCents
	if o.MeterMonth.IsSet() {
		toSerialize["meter_month"] = o.MeterMonth.Get()
	}
	toSerialize["monthly_cap_cents"] = o.MonthlyCapCents
	toSerialize["target_eur_cents"] = o.TargetEurCents
	return toSerialize, nil
}

func (o *AutoRechargeState) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"below_eur_cents",
		"enabled",
		"has_stripe_customer",
		"meter_cents",
		"monthly_cap_cents",
		"target_eur_cents",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAutoRechargeState := _AutoRechargeState{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAutoRechargeState)

	if err != nil {
		return err
	}

	*o = AutoRechargeState(varAutoRechargeState)

	return err
}

type NullableAutoRechargeState struct {
	value *AutoRechargeState
	isSet bool
}

func (v NullableAutoRechargeState) Get() *AutoRechargeState {
	return v.value
}

func (v *NullableAutoRechargeState) Set(val *AutoRechargeState) {
	v.value = val
	v.isSet = true
}

func (v NullableAutoRechargeState) IsSet() bool {
	return v.isSet
}

func (v *NullableAutoRechargeState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAutoRechargeState(val *AutoRechargeState) *NullableAutoRechargeState {
	return &NullableAutoRechargeState{value: val, isSet: true}
}

func (v NullableAutoRechargeState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAutoRechargeState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


