/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeResponse{}

// MeResponse Authenticated user snapshot. All monetary fields are integer EUR cents (1 EUR = 100 cents). 
type MeResponse struct {
	// Current pricing tier level. Higher levels unlock better rate limits and job concurrency.
	ApiUsageTier int32 `json:"api_usage_tier"`
	AutoRecharge *AutoRechargeState `json:"auto_recharge,omitempty"`
	// Spendable balance in EUR cents — `balance_eur_cents` minus any credits held for in-flight async jobs.
	AvailableEurCents int64 `json:"available_eur_cents"`
	// Total credit balance in EUR cents, before deducting active holds.
	BalanceEurCents int64 `json:"balance_eur_cents"`
	// Active credit grants (non-empty, unexpired), consumed in `expires_at` ascending order.
	EuroTranches []EuroTranche `json:"euro_tranches"`
	// True once the account has completed at least one successful Stripe payment.
	HasEverPaid bool `json:"has_ever_paid"`
	// Cumulative EUR cents charged across all Stripe payments, all time.
	LifetimePaidCents int64 `json:"lifetime_paid_cents"`
	// Total number of successful Stripe payments on this account.
	PaymentCount int32 `json:"payment_count"`
	// Account role. `admin` accounts can sign in to the staff back-office; regular accounts are `user`.
	Role string `json:"role"`
	SignupTrial NullableMeResponseSignupTrial `json:"signup_trial,omitempty"`
	UserId string `json:"user_id"`
}

type _MeResponse MeResponse

// NewMeResponse instantiates a new MeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeResponse(apiUsageTier int32, availableEurCents int64, balanceEurCents int64, euroTranches []EuroTranche, hasEverPaid bool, lifetimePaidCents int64, paymentCount int32, role string, userId string) *MeResponse {
	this := MeResponse{}
	this.ApiUsageTier = apiUsageTier
	this.AvailableEurCents = availableEurCents
	this.BalanceEurCents = balanceEurCents
	this.EuroTranches = euroTranches
	this.HasEverPaid = hasEverPaid
	this.LifetimePaidCents = lifetimePaidCents
	this.PaymentCount = paymentCount
	this.Role = role
	this.UserId = userId
	return &this
}

// NewMeResponseWithDefaults instantiates a new MeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeResponseWithDefaults() *MeResponse {
	this := MeResponse{}
	return &this
}

// GetApiUsageTier returns the ApiUsageTier field value
func (o *MeResponse) GetApiUsageTier() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ApiUsageTier
}

// GetApiUsageTierOk returns a tuple with the ApiUsageTier field value
// and a boolean to check if the value has been set.
func (o *MeResponse) GetApiUsageTierOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiUsageTier, true
}

// SetApiUsageTier sets field value
func (o *MeResponse) SetApiUsageTier(v int32) {
	o.ApiUsageTier = v
}

// GetAutoRecharge returns the AutoRecharge field value if set, zero value otherwise.
func (o *MeResponse) GetAutoRecharge() AutoRechargeState {
	if o == nil || IsNil(o.AutoRecharge) {
		var ret AutoRechargeState
		return ret
	}
	return *o.AutoRecharge
}

// GetAutoRechargeOk returns a tuple with the AutoRecharge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeResponse) GetAutoRechargeOk() (*AutoRechargeState, bool) {
	if o == nil || IsNil(o.AutoRecharge) {
		return nil, false
	}
	return o.AutoRecharge, true
}

// HasAutoRecharge returns a boolean if a field has been set.
func (o *MeResponse) HasAutoRecharge() bool {
	if o != nil && !IsNil(o.AutoRecharge) {
		return true
	}

	return false
}

// SetAutoRecharge gets a reference to the given AutoRechargeState and assigns it to the AutoRecharge field.
func (o *MeResponse) SetAutoRecharge(v AutoRechargeState) {
	o.AutoRecharge = &v
}

// GetAvailableEurCents returns the AvailableEurCents field value
func (o *MeResponse) GetAvailableEurCents() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AvailableEurCents
}

// GetAvailableEurCentsOk returns a tuple with the AvailableEurCents field value
// and a boolean to check if the value has been set.
func (o *MeResponse) GetAvailableEurCentsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AvailableEurCents, true
}

// SetAvailableEurCents sets field value
func (o *MeResponse) SetAvailableEurCents(v int64) {
	o.AvailableEurCents = v
}

// GetBalanceEurCents returns the BalanceEurCents field value
func (o *MeResponse) GetBalanceEurCents() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.BalanceEurCents
}

// GetBalanceEurCentsOk returns a tuple with the BalanceEurCents field value
// and a boolean to check if the value has been set.
func (o *MeResponse) GetBalanceEurCentsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BalanceEurCents, true
}

// SetBalanceEurCents sets field value
func (o *MeResponse) SetBalanceEurCents(v int64) {
	o.BalanceEurCents = v
}

// GetEuroTranches returns the EuroTranches field value
func (o *MeResponse) GetEuroTranches() []EuroTranche {
	if o == nil {
		var ret []EuroTranche
		return ret
	}

	return o.EuroTranches
}

// GetEuroTranchesOk returns a tuple with the EuroTranches field value
// and a boolean to check if the value has been set.
func (o *MeResponse) GetEuroTranchesOk() ([]EuroTranche, bool) {
	if o == nil {
		return nil, false
	}
	return o.EuroTranches, true
}

// SetEuroTranches sets field value
func (o *MeResponse) SetEuroTranches(v []EuroTranche) {
	o.EuroTranches = v
}

// GetHasEverPaid returns the HasEverPaid field value
func (o *MeResponse) GetHasEverPaid() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasEverPaid
}

// GetHasEverPaidOk returns a tuple with the HasEverPaid field value
// and a boolean to check if the value has been set.
func (o *MeResponse) GetHasEverPaidOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasEverPaid, true
}

// SetHasEverPaid sets field value
func (o *MeResponse) SetHasEverPaid(v bool) {
	o.HasEverPaid = v
}

// GetLifetimePaidCents returns the LifetimePaidCents field value
func (o *MeResponse) GetLifetimePaidCents() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LifetimePaidCents
}

// GetLifetimePaidCentsOk returns a tuple with the LifetimePaidCents field value
// and a boolean to check if the value has been set.
func (o *MeResponse) GetLifetimePaidCentsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LifetimePaidCents, true
}

// SetLifetimePaidCents sets field value
func (o *MeResponse) SetLifetimePaidCents(v int64) {
	o.LifetimePaidCents = v
}

// GetPaymentCount returns the PaymentCount field value
func (o *MeResponse) GetPaymentCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PaymentCount
}

// GetPaymentCountOk returns a tuple with the PaymentCount field value
// and a boolean to check if the value has been set.
func (o *MeResponse) GetPaymentCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentCount, true
}

// SetPaymentCount sets field value
func (o *MeResponse) SetPaymentCount(v int32) {
	o.PaymentCount = v
}

// GetRole returns the Role field value
func (o *MeResponse) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *MeResponse) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *MeResponse) SetRole(v string) {
	o.Role = v
}

// GetSignupTrial returns the SignupTrial field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MeResponse) GetSignupTrial() MeResponseSignupTrial {
	if o == nil || IsNil(o.SignupTrial.Get()) {
		var ret MeResponseSignupTrial
		return ret
	}
	return *o.SignupTrial.Get()
}

// GetSignupTrialOk returns a tuple with the SignupTrial field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MeResponse) GetSignupTrialOk() (*MeResponseSignupTrial, bool) {
	if o == nil {
		return nil, false
	}
	return o.SignupTrial.Get(), o.SignupTrial.IsSet()
}

// HasSignupTrial returns a boolean if a field has been set.
func (o *MeResponse) HasSignupTrial() bool {
	if o != nil && o.SignupTrial.IsSet() {
		return true
	}

	return false
}

// SetSignupTrial gets a reference to the given NullableMeResponseSignupTrial and assigns it to the SignupTrial field.
func (o *MeResponse) SetSignupTrial(v MeResponseSignupTrial) {
	o.SignupTrial.Set(&v)
}
// SetSignupTrialNil sets the value for SignupTrial to be an explicit nil
func (o *MeResponse) SetSignupTrialNil() {
	o.SignupTrial.Set(nil)
}

// UnsetSignupTrial ensures that no value is present for SignupTrial, not even an explicit nil
func (o *MeResponse) UnsetSignupTrial() {
	o.SignupTrial.Unset()
}

// GetUserId returns the UserId field value
func (o *MeResponse) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *MeResponse) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *MeResponse) SetUserId(v string) {
	o.UserId = v
}

func (o MeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["api_usage_tier"] = o.ApiUsageTier
	if !IsNil(o.AutoRecharge) {
		toSerialize["auto_recharge"] = o.AutoRecharge
	}
	toSerialize["available_eur_cents"] = o.AvailableEurCents
	toSerialize["balance_eur_cents"] = o.BalanceEurCents
	toSerialize["euro_tranches"] = o.EuroTranches
	toSerialize["has_ever_paid"] = o.HasEverPaid
	toSerialize["lifetime_paid_cents"] = o.LifetimePaidCents
	toSerialize["payment_count"] = o.PaymentCount
	toSerialize["role"] = o.Role
	if o.SignupTrial.IsSet() {
		toSerialize["signup_trial"] = o.SignupTrial.Get()
	}
	toSerialize["user_id"] = o.UserId
	return toSerialize, nil
}

func (o *MeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"api_usage_tier",
		"available_eur_cents",
		"balance_eur_cents",
		"euro_tranches",
		"has_ever_paid",
		"lifetime_paid_cents",
		"payment_count",
		"role",
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMeResponse := _MeResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMeResponse)

	if err != nil {
		return err
	}

	*o = MeResponse(varMeResponse)

	return err
}

type NullableMeResponse struct {
	value *MeResponse
	isSet bool
}

func (v NullableMeResponse) Get() *MeResponse {
	return v.value
}

func (v *NullableMeResponse) Set(val *MeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeResponse(val *MeResponse) *NullableMeResponse {
	return &NullableMeResponse{value: val, isSet: true}
}

func (v NullableMeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


