/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
)

// checks if the HealthGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthGet200Response{}

// HealthGet200Response struct for HealthGet200Response
type HealthGet200Response struct {
	// Overall health — \"ok\" when all components are healthy, \"degraded\" otherwise.
	Status *string `json:"status,omitempty"`
	// Per-component status map. Keys are functional names (e.g. data_storage, workflow_engine).
	Components *map[string]HealthGet200ResponseComponentsValue `json:"components,omitempty"`
}

// NewHealthGet200Response instantiates a new HealthGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthGet200Response() *HealthGet200Response {
	this := HealthGet200Response{}
	return &this
}

// NewHealthGet200ResponseWithDefaults instantiates a new HealthGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthGet200ResponseWithDefaults() *HealthGet200Response {
	this := HealthGet200Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *HealthGet200Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthGet200Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *HealthGet200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *HealthGet200Response) SetStatus(v string) {
	o.Status = &v
}

// GetComponents returns the Components field value if set, zero value otherwise.
func (o *HealthGet200Response) GetComponents() map[string]HealthGet200ResponseComponentsValue {
	if o == nil || IsNil(o.Components) {
		var ret map[string]HealthGet200ResponseComponentsValue
		return ret
	}
	return *o.Components
}

// GetComponentsOk returns a tuple with the Components field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthGet200Response) GetComponentsOk() (*map[string]HealthGet200ResponseComponentsValue, bool) {
	if o == nil || IsNil(o.Components) {
		return nil, false
	}
	return o.Components, true
}

// HasComponents returns a boolean if a field has been set.
func (o *HealthGet200Response) HasComponents() bool {
	if o != nil && !IsNil(o.Components) {
		return true
	}

	return false
}

// SetComponents gets a reference to the given map[string]HealthGet200ResponseComponentsValue and assigns it to the Components field.
func (o *HealthGet200Response) SetComponents(v map[string]HealthGet200ResponseComponentsValue) {
	o.Components = &v
}

func (o HealthGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Components) {
		toSerialize["components"] = o.Components
	}
	return toSerialize, nil
}

type NullableHealthGet200Response struct {
	value *HealthGet200Response
	isSet bool
}

func (v NullableHealthGet200Response) Get() *HealthGet200Response {
	return v.value
}

func (v *NullableHealthGet200Response) Set(val *HealthGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthGet200Response(val *HealthGet200Response) *NullableHealthGet200Response {
	return &NullableHealthGet200Response{value: val, isSet: true}
}

func (v NullableHealthGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


