/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
	"time"
)

// checks if the MeResponseSignupTrial type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeResponseSignupTrial{}

// MeResponseSignupTrial Present when a free trial tranche was granted at signup. Omitted for accounts with no trial.
type MeResponseSignupTrial struct {
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	GrantedAt *time.Time `json:"granted_at,omitempty"`
	InitialEurCents *int64 `json:"initial_eur_cents,omitempty"`
	RemainingEurCents *int64 `json:"remaining_eur_cents,omitempty"`
}

// NewMeResponseSignupTrial instantiates a new MeResponseSignupTrial object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeResponseSignupTrial() *MeResponseSignupTrial {
	this := MeResponseSignupTrial{}
	return &this
}

// NewMeResponseSignupTrialWithDefaults instantiates a new MeResponseSignupTrial object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeResponseSignupTrialWithDefaults() *MeResponseSignupTrial {
	this := MeResponseSignupTrial{}
	return &this
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *MeResponseSignupTrial) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeResponseSignupTrial) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *MeResponseSignupTrial) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *MeResponseSignupTrial) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetGrantedAt returns the GrantedAt field value if set, zero value otherwise.
func (o *MeResponseSignupTrial) GetGrantedAt() time.Time {
	if o == nil || IsNil(o.GrantedAt) {
		var ret time.Time
		return ret
	}
	return *o.GrantedAt
}

// GetGrantedAtOk returns a tuple with the GrantedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeResponseSignupTrial) GetGrantedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.GrantedAt) {
		return nil, false
	}
	return o.GrantedAt, true
}

// HasGrantedAt returns a boolean if a field has been set.
func (o *MeResponseSignupTrial) HasGrantedAt() bool {
	if o != nil && !IsNil(o.GrantedAt) {
		return true
	}

	return false
}

// SetGrantedAt gets a reference to the given time.Time and assigns it to the GrantedAt field.
func (o *MeResponseSignupTrial) SetGrantedAt(v time.Time) {
	o.GrantedAt = &v
}

// GetInitialEurCents returns the InitialEurCents field value if set, zero value otherwise.
func (o *MeResponseSignupTrial) GetInitialEurCents() int64 {
	if o == nil || IsNil(o.InitialEurCents) {
		var ret int64
		return ret
	}
	return *o.InitialEurCents
}

// GetInitialEurCentsOk returns a tuple with the InitialEurCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeResponseSignupTrial) GetInitialEurCentsOk() (*int64, bool) {
	if o == nil || IsNil(o.InitialEurCents) {
		return nil, false
	}
	return o.InitialEurCents, true
}

// HasInitialEurCents returns a boolean if a field has been set.
func (o *MeResponseSignupTrial) HasInitialEurCents() bool {
	if o != nil && !IsNil(o.InitialEurCents) {
		return true
	}

	return false
}

// SetInitialEurCents gets a reference to the given int64 and assigns it to the InitialEurCents field.
func (o *MeResponseSignupTrial) SetInitialEurCents(v int64) {
	o.InitialEurCents = &v
}

// GetRemainingEurCents returns the RemainingEurCents field value if set, zero value otherwise.
func (o *MeResponseSignupTrial) GetRemainingEurCents() int64 {
	if o == nil || IsNil(o.RemainingEurCents) {
		var ret int64
		return ret
	}
	return *o.RemainingEurCents
}

// GetRemainingEurCentsOk returns a tuple with the RemainingEurCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MeResponseSignupTrial) GetRemainingEurCentsOk() (*int64, bool) {
	if o == nil || IsNil(o.RemainingEurCents) {
		return nil, false
	}
	return o.RemainingEurCents, true
}

// HasRemainingEurCents returns a boolean if a field has been set.
func (o *MeResponseSignupTrial) HasRemainingEurCents() bool {
	if o != nil && !IsNil(o.RemainingEurCents) {
		return true
	}

	return false
}

// SetRemainingEurCents gets a reference to the given int64 and assigns it to the RemainingEurCents field.
func (o *MeResponseSignupTrial) SetRemainingEurCents(v int64) {
	o.RemainingEurCents = &v
}

func (o MeResponseSignupTrial) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MeResponseSignupTrial) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	if !IsNil(o.GrantedAt) {
		toSerialize["granted_at"] = o.GrantedAt
	}
	if !IsNil(o.InitialEurCents) {
		toSerialize["initial_eur_cents"] = o.InitialEurCents
	}
	if !IsNil(o.RemainingEurCents) {
		toSerialize["remaining_eur_cents"] = o.RemainingEurCents
	}
	return toSerialize, nil
}

type NullableMeResponseSignupTrial struct {
	value *MeResponseSignupTrial
	isSet bool
}

func (v NullableMeResponseSignupTrial) Get() *MeResponseSignupTrial {
	return v.value
}

func (v *NullableMeResponseSignupTrial) Set(val *MeResponseSignupTrial) {
	v.value = val
	v.isSet = true
}

func (v NullableMeResponseSignupTrial) IsSet() bool {
	return v.isSet
}

func (v *NullableMeResponseSignupTrial) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeResponseSignupTrial(val *MeResponseSignupTrial) *NullableMeResponseSignupTrial {
	return &NullableMeResponseSignupTrial{value: val, isSet: true}
}

func (v NullableMeResponseSignupTrial) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeResponseSignupTrial) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


