/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
	"time"
)

// checks if the NewsItemV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewsItemV1{}

// NewsItemV1 A news article associated with an alert.
type NewsItemV1 struct {
	// Topical category of the article (e.g. `world`, `business`, `energy`).
	Category *string `json:"category,omitempty"`
	// Short summary of the article.
	Description *string `json:"description,omitempty"`
	// Publication timestamp (RFC 3339 / ISO 8601).
	PublishedAt *time.Time `json:"published_at,omitempty"`
	// Name of the publication or media outlet.
	SourceName *string `json:"source_name,omitempty"`
	// Headline of the news article.
	Title *string `json:"title,omitempty"`
	// Whether this article is currently trending across the platform.
	Trending *bool `json:"trending,omitempty"`
	// Canonical URL of the article.
	Url *string `json:"url,omitempty"`
}

// NewNewsItemV1 instantiates a new NewsItemV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewsItemV1() *NewsItemV1 {
	this := NewsItemV1{}
	return &this
}

// NewNewsItemV1WithDefaults instantiates a new NewsItemV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewsItemV1WithDefaults() *NewsItemV1 {
	this := NewsItemV1{}
	return &this
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *NewsItemV1) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewsItemV1) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *NewsItemV1) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *NewsItemV1) SetCategory(v string) {
	o.Category = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *NewsItemV1) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewsItemV1) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *NewsItemV1) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *NewsItemV1) SetDescription(v string) {
	o.Description = &v
}

// GetPublishedAt returns the PublishedAt field value if set, zero value otherwise.
func (o *NewsItemV1) GetPublishedAt() time.Time {
	if o == nil || IsNil(o.PublishedAt) {
		var ret time.Time
		return ret
	}
	return *o.PublishedAt
}

// GetPublishedAtOk returns a tuple with the PublishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewsItemV1) GetPublishedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PublishedAt) {
		return nil, false
	}
	return o.PublishedAt, true
}

// HasPublishedAt returns a boolean if a field has been set.
func (o *NewsItemV1) HasPublishedAt() bool {
	if o != nil && !IsNil(o.PublishedAt) {
		return true
	}

	return false
}

// SetPublishedAt gets a reference to the given time.Time and assigns it to the PublishedAt field.
func (o *NewsItemV1) SetPublishedAt(v time.Time) {
	o.PublishedAt = &v
}

// GetSourceName returns the SourceName field value if set, zero value otherwise.
func (o *NewsItemV1) GetSourceName() string {
	if o == nil || IsNil(o.SourceName) {
		var ret string
		return ret
	}
	return *o.SourceName
}

// GetSourceNameOk returns a tuple with the SourceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewsItemV1) GetSourceNameOk() (*string, bool) {
	if o == nil || IsNil(o.SourceName) {
		return nil, false
	}
	return o.SourceName, true
}

// HasSourceName returns a boolean if a field has been set.
func (o *NewsItemV1) HasSourceName() bool {
	if o != nil && !IsNil(o.SourceName) {
		return true
	}

	return false
}

// SetSourceName gets a reference to the given string and assigns it to the SourceName field.
func (o *NewsItemV1) SetSourceName(v string) {
	o.SourceName = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *NewsItemV1) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewsItemV1) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *NewsItemV1) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *NewsItemV1) SetTitle(v string) {
	o.Title = &v
}

// GetTrending returns the Trending field value if set, zero value otherwise.
func (o *NewsItemV1) GetTrending() bool {
	if o == nil || IsNil(o.Trending) {
		var ret bool
		return ret
	}
	return *o.Trending
}

// GetTrendingOk returns a tuple with the Trending field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewsItemV1) GetTrendingOk() (*bool, bool) {
	if o == nil || IsNil(o.Trending) {
		return nil, false
	}
	return o.Trending, true
}

// HasTrending returns a boolean if a field has been set.
func (o *NewsItemV1) HasTrending() bool {
	if o != nil && !IsNil(o.Trending) {
		return true
	}

	return false
}

// SetTrending gets a reference to the given bool and assigns it to the Trending field.
func (o *NewsItemV1) SetTrending(v bool) {
	o.Trending = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *NewsItemV1) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewsItemV1) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *NewsItemV1) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *NewsItemV1) SetUrl(v string) {
	o.Url = &v
}

func (o NewsItemV1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewsItemV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.PublishedAt) {
		toSerialize["published_at"] = o.PublishedAt
	}
	if !IsNil(o.SourceName) {
		toSerialize["source_name"] = o.SourceName
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Trending) {
		toSerialize["trending"] = o.Trending
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableNewsItemV1 struct {
	value *NewsItemV1
	isSet bool
}

func (v NullableNewsItemV1) Get() *NewsItemV1 {
	return v.value
}

func (v *NullableNewsItemV1) Set(val *NewsItemV1) {
	v.value = val
	v.isSet = true
}

func (v NullableNewsItemV1) IsSet() bool {
	return v.isSet
}

func (v *NullableNewsItemV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewsItemV1(val *NewsItemV1) *NullableNewsItemV1 {
	return &NullableNewsItemV1{value: val, isSet: true}
}

func (v NullableNewsItemV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewsItemV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


