/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CategoryListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CategoryListResponse{}

// CategoryListResponse struct for CategoryListResponse
type CategoryListResponse struct {
	// Complete category listing, sorted by id ascending. No pagination.
	Items []CategoryItemV1 `json:"items"`
}

type _CategoryListResponse CategoryListResponse

// NewCategoryListResponse instantiates a new CategoryListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCategoryListResponse(items []CategoryItemV1) *CategoryListResponse {
	this := CategoryListResponse{}
	this.Items = items
	return &this
}

// NewCategoryListResponseWithDefaults instantiates a new CategoryListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCategoryListResponseWithDefaults() *CategoryListResponse {
	this := CategoryListResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *CategoryListResponse) GetItems() []CategoryItemV1 {
	if o == nil {
		var ret []CategoryItemV1
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *CategoryListResponse) GetItemsOk() ([]CategoryItemV1, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *CategoryListResponse) SetItems(v []CategoryItemV1) {
	o.Items = v
}

func (o CategoryListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CategoryListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *CategoryListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCategoryListResponse := _CategoryListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCategoryListResponse)

	if err != nil {
		return err
	}

	*o = CategoryListResponse(varCategoryListResponse)

	return err
}

type NullableCategoryListResponse struct {
	value *CategoryListResponse
	isSet bool
}

func (v NullableCategoryListResponse) Get() *CategoryListResponse {
	return v.value
}

func (v *NullableCategoryListResponse) Set(val *CategoryListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCategoryListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCategoryListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCategoryListResponse(val *CategoryListResponse) *NullableCategoryListResponse {
	return &NullableCategoryListResponse{value: val, isSet: true}
}

func (v NullableCategoryListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCategoryListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


