/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RecommendRequestV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecommendRequestV1{}

// RecommendRequestV1 Body of `POST /api/v1/drivers`. Mirrors the upstream Recommend service contract. Note that the version field is named `version` (not `pipeline_version` as on `/forecasts`).  Required fields: `version`, `recency_factor`, `timeseries_metadata`. Both `filters` and `timeseries` are optional on the recommend endpoint — when omitted, the handler drops them from the upstream payload entirely (no `null` is sent).  When `filters` is present, **`categories[]`** and **`regions[]`** follow the same rules as `POST /api/v1/forecasts`: each integer must be **1–9999** inclusive; optional **`limit`** is **0–10000**. See schema **`Filters`** for the canonical shape. 
type RecommendRequestV1 struct {
	// Optional. Same validation as **`POST /api/v1/forecasts`**: each **`categories[]`** and **`regions[]`** entry is an integer **1–9999** (inclusive); optional **`limit`** is **0–10000**. Values are not verified against catalog APIs. 
	Filters *Filters `json:"filters,omitempty"`
	RecencyFactor float64 `json:"recency_factor"`
	// Optional. Map of YYYY-MM-DD date keys to numeric observation values. When supplied, all keys must parse as YYYY-MM-DD and all values must be finite. Unlike `/forecasts`, this endpoint is frequency-agnostic — there is no monthly alignment, gap detection, or 60-point minimum. When omitted, the handler does not forward the field to the upstream Recommend service at all. 
	Timeseries *map[string]float32 `json:"timeseries,omitempty"`
	TimeseriesMetadata TimeseriesMetadata `json:"timeseries_metadata"`
	// Recommend pipeline version. Closed set; only v1 is supported today. Used **locally** to select the per-version validator and is **not forwarded** to the upstream Recommend service. 
	Version string `json:"version"`
}

type _RecommendRequestV1 RecommendRequestV1

// NewRecommendRequestV1 instantiates a new RecommendRequestV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecommendRequestV1(recencyFactor float64, timeseriesMetadata TimeseriesMetadata, version string) *RecommendRequestV1 {
	this := RecommendRequestV1{}
	this.RecencyFactor = recencyFactor
	this.TimeseriesMetadata = timeseriesMetadata
	this.Version = version
	return &this
}

// NewRecommendRequestV1WithDefaults instantiates a new RecommendRequestV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecommendRequestV1WithDefaults() *RecommendRequestV1 {
	this := RecommendRequestV1{}
	return &this
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *RecommendRequestV1) GetFilters() Filters {
	if o == nil || IsNil(o.Filters) {
		var ret Filters
		return ret
	}
	return *o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecommendRequestV1) GetFiltersOk() (*Filters, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *RecommendRequestV1) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given Filters and assigns it to the Filters field.
func (o *RecommendRequestV1) SetFilters(v Filters) {
	o.Filters = &v
}

// GetRecencyFactor returns the RecencyFactor field value
func (o *RecommendRequestV1) GetRecencyFactor() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.RecencyFactor
}

// GetRecencyFactorOk returns a tuple with the RecencyFactor field value
// and a boolean to check if the value has been set.
func (o *RecommendRequestV1) GetRecencyFactorOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecencyFactor, true
}

// SetRecencyFactor sets field value
func (o *RecommendRequestV1) SetRecencyFactor(v float64) {
	o.RecencyFactor = v
}

// GetTimeseries returns the Timeseries field value if set, zero value otherwise.
func (o *RecommendRequestV1) GetTimeseries() map[string]float32 {
	if o == nil || IsNil(o.Timeseries) {
		var ret map[string]float32
		return ret
	}
	return *o.Timeseries
}

// GetTimeseriesOk returns a tuple with the Timeseries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecommendRequestV1) GetTimeseriesOk() (*map[string]float32, bool) {
	if o == nil || IsNil(o.Timeseries) {
		return nil, false
	}
	return o.Timeseries, true
}

// HasTimeseries returns a boolean if a field has been set.
func (o *RecommendRequestV1) HasTimeseries() bool {
	if o != nil && !IsNil(o.Timeseries) {
		return true
	}

	return false
}

// SetTimeseries gets a reference to the given map[string]float32 and assigns it to the Timeseries field.
func (o *RecommendRequestV1) SetTimeseries(v map[string]float32) {
	o.Timeseries = &v
}

// GetTimeseriesMetadata returns the TimeseriesMetadata field value
func (o *RecommendRequestV1) GetTimeseriesMetadata() TimeseriesMetadata {
	if o == nil {
		var ret TimeseriesMetadata
		return ret
	}

	return o.TimeseriesMetadata
}

// GetTimeseriesMetadataOk returns a tuple with the TimeseriesMetadata field value
// and a boolean to check if the value has been set.
func (o *RecommendRequestV1) GetTimeseriesMetadataOk() (*TimeseriesMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeseriesMetadata, true
}

// SetTimeseriesMetadata sets field value
func (o *RecommendRequestV1) SetTimeseriesMetadata(v TimeseriesMetadata) {
	o.TimeseriesMetadata = v
}

// GetVersion returns the Version field value
func (o *RecommendRequestV1) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *RecommendRequestV1) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *RecommendRequestV1) SetVersion(v string) {
	o.Version = v
}

func (o RecommendRequestV1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecommendRequestV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	toSerialize["recency_factor"] = o.RecencyFactor
	if !IsNil(o.Timeseries) {
		toSerialize["timeseries"] = o.Timeseries
	}
	toSerialize["timeseries_metadata"] = o.TimeseriesMetadata
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *RecommendRequestV1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"recency_factor",
		"timeseries_metadata",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecommendRequestV1 := _RecommendRequestV1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecommendRequestV1)

	if err != nil {
		return err
	}

	*o = RecommendRequestV1(varRecommendRequestV1)

	return err
}

type NullableRecommendRequestV1 struct {
	value *RecommendRequestV1
	isSet bool
}

func (v NullableRecommendRequestV1) Get() *RecommendRequestV1 {
	return v.value
}

func (v *NullableRecommendRequestV1) Set(val *RecommendRequestV1) {
	v.value = val
	v.isSet = true
}

func (v NullableRecommendRequestV1) IsSet() bool {
	return v.isSet
}

func (v *NullableRecommendRequestV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecommendRequestV1(val *RecommendRequestV1) *NullableRecommendRequestV1 {
	return &NullableRecommendRequestV1{value: val, isSet: true}
}

func (v NullableRecommendRequestV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecommendRequestV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


