/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
)

// checks if the HealthGet200ResponseComponentsValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthGet200ResponseComponentsValue{}

// HealthGet200ResponseComponentsValue struct for HealthGet200ResponseComponentsValue
type HealthGet200ResponseComponentsValue struct {
	Status *string `json:"status,omitempty"`
}

// NewHealthGet200ResponseComponentsValue instantiates a new HealthGet200ResponseComponentsValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthGet200ResponseComponentsValue() *HealthGet200ResponseComponentsValue {
	this := HealthGet200ResponseComponentsValue{}
	return &this
}

// NewHealthGet200ResponseComponentsValueWithDefaults instantiates a new HealthGet200ResponseComponentsValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthGet200ResponseComponentsValueWithDefaults() *HealthGet200ResponseComponentsValue {
	this := HealthGet200ResponseComponentsValue{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *HealthGet200ResponseComponentsValue) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthGet200ResponseComponentsValue) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *HealthGet200ResponseComponentsValue) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *HealthGet200ResponseComponentsValue) SetStatus(v string) {
	o.Status = &v
}

func (o HealthGet200ResponseComponentsValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthGet200ResponseComponentsValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableHealthGet200ResponseComponentsValue struct {
	value *HealthGet200ResponseComponentsValue
	isSet bool
}

func (v NullableHealthGet200ResponseComponentsValue) Get() *HealthGet200ResponseComponentsValue {
	return v.value
}

func (v *NullableHealthGet200ResponseComponentsValue) Set(val *HealthGet200ResponseComponentsValue) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthGet200ResponseComponentsValue) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthGet200ResponseComponentsValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthGet200ResponseComponentsValue(val *HealthGet200ResponseComponentsValue) *NullableHealthGet200ResponseComponentsValue {
	return &NullableHealthGet200ResponseComponentsValue{value: val, isSet: true}
}

func (v NullableHealthGet200ResponseComponentsValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthGet200ResponseComponentsValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


