/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
)

// checks if the ApiV1ForecastsPost202Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV1ForecastsPost202Response{}

// ApiV1ForecastsPost202Response struct for ApiV1ForecastsPost202Response
type ApiV1ForecastsPost202Response struct {
	// Unique job id — use this to poll status and download artifacts.
	JobId *string `json:"job_id,omitempty"`
	// Convenience URL for polling this job's status.
	PollUrl *string `json:"poll_url,omitempty"`
	// Internal run identifier (opaque; useful for support).
	RunId *string `json:"run_id,omitempty"`
	// Internal workflow identifier (opaque; useful for support).
	Workflow *string `json:"workflow,omitempty"`
}

// NewApiV1ForecastsPost202Response instantiates a new ApiV1ForecastsPost202Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1ForecastsPost202Response() *ApiV1ForecastsPost202Response {
	this := ApiV1ForecastsPost202Response{}
	return &this
}

// NewApiV1ForecastsPost202ResponseWithDefaults instantiates a new ApiV1ForecastsPost202Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1ForecastsPost202ResponseWithDefaults() *ApiV1ForecastsPost202Response {
	this := ApiV1ForecastsPost202Response{}
	return &this
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *ApiV1ForecastsPost202Response) GetJobId() string {
	if o == nil || IsNil(o.JobId) {
		var ret string
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1ForecastsPost202Response) GetJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *ApiV1ForecastsPost202Response) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given string and assigns it to the JobId field.
func (o *ApiV1ForecastsPost202Response) SetJobId(v string) {
	o.JobId = &v
}

// GetPollUrl returns the PollUrl field value if set, zero value otherwise.
func (o *ApiV1ForecastsPost202Response) GetPollUrl() string {
	if o == nil || IsNil(o.PollUrl) {
		var ret string
		return ret
	}
	return *o.PollUrl
}

// GetPollUrlOk returns a tuple with the PollUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1ForecastsPost202Response) GetPollUrlOk() (*string, bool) {
	if o == nil || IsNil(o.PollUrl) {
		return nil, false
	}
	return o.PollUrl, true
}

// HasPollUrl returns a boolean if a field has been set.
func (o *ApiV1ForecastsPost202Response) HasPollUrl() bool {
	if o != nil && !IsNil(o.PollUrl) {
		return true
	}

	return false
}

// SetPollUrl gets a reference to the given string and assigns it to the PollUrl field.
func (o *ApiV1ForecastsPost202Response) SetPollUrl(v string) {
	o.PollUrl = &v
}

// GetRunId returns the RunId field value if set, zero value otherwise.
func (o *ApiV1ForecastsPost202Response) GetRunId() string {
	if o == nil || IsNil(o.RunId) {
		var ret string
		return ret
	}
	return *o.RunId
}

// GetRunIdOk returns a tuple with the RunId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1ForecastsPost202Response) GetRunIdOk() (*string, bool) {
	if o == nil || IsNil(o.RunId) {
		return nil, false
	}
	return o.RunId, true
}

// HasRunId returns a boolean if a field has been set.
func (o *ApiV1ForecastsPost202Response) HasRunId() bool {
	if o != nil && !IsNil(o.RunId) {
		return true
	}

	return false
}

// SetRunId gets a reference to the given string and assigns it to the RunId field.
func (o *ApiV1ForecastsPost202Response) SetRunId(v string) {
	o.RunId = &v
}

// GetWorkflow returns the Workflow field value if set, zero value otherwise.
func (o *ApiV1ForecastsPost202Response) GetWorkflow() string {
	if o == nil || IsNil(o.Workflow) {
		var ret string
		return ret
	}
	return *o.Workflow
}

// GetWorkflowOk returns a tuple with the Workflow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1ForecastsPost202Response) GetWorkflowOk() (*string, bool) {
	if o == nil || IsNil(o.Workflow) {
		return nil, false
	}
	return o.Workflow, true
}

// HasWorkflow returns a boolean if a field has been set.
func (o *ApiV1ForecastsPost202Response) HasWorkflow() bool {
	if o != nil && !IsNil(o.Workflow) {
		return true
	}

	return false
}

// SetWorkflow gets a reference to the given string and assigns it to the Workflow field.
func (o *ApiV1ForecastsPost202Response) SetWorkflow(v string) {
	o.Workflow = &v
}

func (o ApiV1ForecastsPost202Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV1ForecastsPost202Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.JobId) {
		toSerialize["job_id"] = o.JobId
	}
	if !IsNil(o.PollUrl) {
		toSerialize["poll_url"] = o.PollUrl
	}
	if !IsNil(o.RunId) {
		toSerialize["run_id"] = o.RunId
	}
	if !IsNil(o.Workflow) {
		toSerialize["workflow"] = o.Workflow
	}
	return toSerialize, nil
}

type NullableApiV1ForecastsPost202Response struct {
	value *ApiV1ForecastsPost202Response
	isSet bool
}

func (v NullableApiV1ForecastsPost202Response) Get() *ApiV1ForecastsPost202Response {
	return v.value
}

func (v *NullableApiV1ForecastsPost202Response) Set(val *ApiV1ForecastsPost202Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1ForecastsPost202Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1ForecastsPost202Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1ForecastsPost202Response(val *ApiV1ForecastsPost202Response) *NullableApiV1ForecastsPost202Response {
	return &NullableApiV1ForecastsPost202Response{value: val, isSet: true}
}

func (v NullableApiV1ForecastsPost202Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1ForecastsPost202Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


