/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
)

// checks if the DriverItemV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DriverItemV1{}

// DriverItemV1 A ranked dataset candidate returned by `POST /api/v1/drivers`.
type DriverItemV1 struct {
	// Human-readable name of the dataset.
	DriverName *string `json:"driver_name,omitempty"`
	// Stable identifier for the dataset; use to reference this driver across requests.
	HashId *string `json:"hash_id,omitempty"`
	// Relevance score indicating how well this dataset explains your timeseries (higher is more relevant).
	Score *float64 `json:"score,omitempty"`
}

// NewDriverItemV1 instantiates a new DriverItemV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDriverItemV1() *DriverItemV1 {
	this := DriverItemV1{}
	return &this
}

// NewDriverItemV1WithDefaults instantiates a new DriverItemV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDriverItemV1WithDefaults() *DriverItemV1 {
	this := DriverItemV1{}
	return &this
}

// GetDriverName returns the DriverName field value if set, zero value otherwise.
func (o *DriverItemV1) GetDriverName() string {
	if o == nil || IsNil(o.DriverName) {
		var ret string
		return ret
	}
	return *o.DriverName
}

// GetDriverNameOk returns a tuple with the DriverName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DriverItemV1) GetDriverNameOk() (*string, bool) {
	if o == nil || IsNil(o.DriverName) {
		return nil, false
	}
	return o.DriverName, true
}

// HasDriverName returns a boolean if a field has been set.
func (o *DriverItemV1) HasDriverName() bool {
	if o != nil && !IsNil(o.DriverName) {
		return true
	}

	return false
}

// SetDriverName gets a reference to the given string and assigns it to the DriverName field.
func (o *DriverItemV1) SetDriverName(v string) {
	o.DriverName = &v
}

// GetHashId returns the HashId field value if set, zero value otherwise.
func (o *DriverItemV1) GetHashId() string {
	if o == nil || IsNil(o.HashId) {
		var ret string
		return ret
	}
	return *o.HashId
}

// GetHashIdOk returns a tuple with the HashId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DriverItemV1) GetHashIdOk() (*string, bool) {
	if o == nil || IsNil(o.HashId) {
		return nil, false
	}
	return o.HashId, true
}

// HasHashId returns a boolean if a field has been set.
func (o *DriverItemV1) HasHashId() bool {
	if o != nil && !IsNil(o.HashId) {
		return true
	}

	return false
}

// SetHashId gets a reference to the given string and assigns it to the HashId field.
func (o *DriverItemV1) SetHashId(v string) {
	o.HashId = &v
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *DriverItemV1) GetScore() float64 {
	if o == nil || IsNil(o.Score) {
		var ret float64
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DriverItemV1) GetScoreOk() (*float64, bool) {
	if o == nil || IsNil(o.Score) {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *DriverItemV1) HasScore() bool {
	if o != nil && !IsNil(o.Score) {
		return true
	}

	return false
}

// SetScore gets a reference to the given float64 and assigns it to the Score field.
func (o *DriverItemV1) SetScore(v float64) {
	o.Score = &v
}

func (o DriverItemV1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DriverItemV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DriverName) {
		toSerialize["driver_name"] = o.DriverName
	}
	if !IsNil(o.HashId) {
		toSerialize["hash_id"] = o.HashId
	}
	if !IsNil(o.Score) {
		toSerialize["score"] = o.Score
	}
	return toSerialize, nil
}

type NullableDriverItemV1 struct {
	value *DriverItemV1
	isSet bool
}

func (v NullableDriverItemV1) Get() *DriverItemV1 {
	return v.value
}

func (v *NullableDriverItemV1) Set(val *DriverItemV1) {
	v.value = val
	v.isSet = true
}

func (v NullableDriverItemV1) IsSet() bool {
	return v.isSet
}

func (v *NullableDriverItemV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDriverItemV1(val *DriverItemV1) *NullableDriverItemV1 {
	return &NullableDriverItemV1{value: val, isSet: true}
}

func (v NullableDriverItemV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDriverItemV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


