/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CategoryItemV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CategoryItemV1{}

// CategoryItemV1 A single thematic category returned by GET /api/v1/categories.
type CategoryItemV1 struct {
	// Integer identifier. Use this value in filters.categories[].
	Id int32 `json:"id"`
	// Human-readable category label.
	Name string `json:"name"`
}

type _CategoryItemV1 CategoryItemV1

// NewCategoryItemV1 instantiates a new CategoryItemV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCategoryItemV1(id int32, name string) *CategoryItemV1 {
	this := CategoryItemV1{}
	this.Id = id
	this.Name = name
	return &this
}

// NewCategoryItemV1WithDefaults instantiates a new CategoryItemV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCategoryItemV1WithDefaults() *CategoryItemV1 {
	this := CategoryItemV1{}
	return &this
}

// GetId returns the Id field value
func (o *CategoryItemV1) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CategoryItemV1) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CategoryItemV1) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *CategoryItemV1) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CategoryItemV1) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CategoryItemV1) SetName(v string) {
	o.Name = v
}

func (o CategoryItemV1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CategoryItemV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *CategoryItemV1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCategoryItemV1 := _CategoryItemV1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCategoryItemV1)

	if err != nil {
		return err
	}

	*o = CategoryItemV1(varCategoryItemV1)

	return err
}

type NullableCategoryItemV1 struct {
	value *CategoryItemV1
	isSet bool
}

func (v NullableCategoryItemV1) Get() *CategoryItemV1 {
	return v.value
}

func (v *NullableCategoryItemV1) Set(val *CategoryItemV1) {
	v.value = val
	v.isSet = true
}

func (v NullableCategoryItemV1) IsSet() bool {
	return v.isSet
}

func (v *NullableCategoryItemV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCategoryItemV1(val *CategoryItemV1) *NullableCategoryItemV1 {
	return &NullableCategoryItemV1{value: val, isSet: true}
}

func (v NullableCategoryItemV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCategoryItemV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
