/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ForecastRequestV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ForecastRequestV1{}

// ForecastRequestV1 Body of `POST /api/v1/forecasts`. Provide at least one of **`soft_horizon`** or **`hard_horizon`** (see property descriptions). Optional **`filters`**: when present, each **`categories[]`** and **`regions[]`** value is an integer **1–9999** inclusive; optional **`limit`** is **0–10000**. See component **`Filters`** for the full schema. 
type ForecastRequestV1 struct {
	// When true, run a backtest evaluation alongside the forecast.
	Backtest *bool `json:"backtest,omitempty"`
	// Optional. Each **`categories[]`** and **`regions[]`** entry must be an integer **1–9999** (inclusive). Optional **`limit`** is **0–10000**. Values are not verified against catalog APIs. 
	Filters *Filters `json:"filters,omitempty"`
	// Series cadence. Only \"monthly\" is currently supported; \"daily\" and \"weekly\" are reserved.
	Frequency string `json:"frequency"`
	// Minimum acceptable horizon (months) for the quality step-down ladder. When omitted, the pipeline falls back to a driverless forecast at `soft_horizon` if no quality run succeeds. When still failing at `hard_horizon`, the pipeline emits a driverless forecast at that horizon. At least one of `soft_horizon` or `hard_horizon` must be present. When both are set, `hard_horizon` must be less than or equal to `soft_horizon`. Maximum 12. 
	HardHorizon *int32 `json:"hard_horizon,omitempty"`
	// Pipeline version. Closed set; no aliases or \"latest\" resolution. Only v1 is supported today.
	PipelineVersion string `json:"pipeline_version"`
	RecencyFactor float64 `json:"recency_factor"`
	// Ideal forecast horizon (months). The pipeline tries this first, then steps down by one month until it reaches `hard_horizon` (when set) while seeking a quality forecast. At least one of `soft_horizon` or `hard_horizon` must be present. When both are set, `hard_horizon` must be less than or equal to `soft_horizon`. Maximum 12. 
	SoftHorizon *int32 `json:"soft_horizon,omitempty"`
	// When true, every value in `timeseries` must be `>= 0` (zero is allowed); a single negative observation rejects the request with 422. The downstream forecasting pipeline (PPL) also clamps the produced forecast at zero so no output point can be negative. Defaults to false, in which case no positivity constraint is applied to inputs or outputs and negative values are returned unchanged. Optional. 
	StrictlyPositive *bool `json:"strictly_positive,omitempty"`
	// Map of YYYY-MM-DD date keys to numeric observation values. Must contain at least 60 points (5 years of monthly history) and be aligned to the declared frequency.
	Timeseries map[string]float32 `json:"timeseries"`
	TimeseriesMetadata TimeseriesMetadata `json:"timeseries_metadata"`
}

type _ForecastRequestV1 ForecastRequestV1

// NewForecastRequestV1 instantiates a new ForecastRequestV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForecastRequestV1(frequency string, pipelineVersion string, recencyFactor float64, timeseries map[string]float32, timeseriesMetadata TimeseriesMetadata) *ForecastRequestV1 {
	this := ForecastRequestV1{}
	this.Frequency = frequency
	this.PipelineVersion = pipelineVersion
	this.RecencyFactor = recencyFactor
	var strictlyPositive bool = false
	this.StrictlyPositive = &strictlyPositive
	this.Timeseries = timeseries
	this.TimeseriesMetadata = timeseriesMetadata
	return &this
}

// NewForecastRequestV1WithDefaults instantiates a new ForecastRequestV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForecastRequestV1WithDefaults() *ForecastRequestV1 {
	this := ForecastRequestV1{}
	var strictlyPositive bool = false
	this.StrictlyPositive = &strictlyPositive
	return &this
}

// GetBacktest returns the Backtest field value if set, zero value otherwise.
func (o *ForecastRequestV1) GetBacktest() bool {
	if o == nil || IsNil(o.Backtest) {
		var ret bool
		return ret
	}
	return *o.Backtest
}

// GetBacktestOk returns a tuple with the Backtest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastRequestV1) GetBacktestOk() (*bool, bool) {
	if o == nil || IsNil(o.Backtest) {
		return nil, false
	}
	return o.Backtest, true
}

// HasBacktest returns a boolean if a field has been set.
func (o *ForecastRequestV1) HasBacktest() bool {
	if o != nil && !IsNil(o.Backtest) {
		return true
	}

	return false
}

// SetBacktest gets a reference to the given bool and assigns it to the Backtest field.
func (o *ForecastRequestV1) SetBacktest(v bool) {
	o.Backtest = &v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *ForecastRequestV1) GetFilters() Filters {
	if o == nil || IsNil(o.Filters) {
		var ret Filters
		return ret
	}
	return *o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastRequestV1) GetFiltersOk() (*Filters, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *ForecastRequestV1) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given Filters and assigns it to the Filters field.
func (o *ForecastRequestV1) SetFilters(v Filters) {
	o.Filters = &v
}

// GetFrequency returns the Frequency field value
func (o *ForecastRequestV1) GetFrequency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value
// and a boolean to check if the value has been set.
func (o *ForecastRequestV1) GetFrequencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Frequency, true
}

// SetFrequency sets field value
func (o *ForecastRequestV1) SetFrequency(v string) {
	o.Frequency = v
}

// GetHardHorizon returns the HardHorizon field value if set, zero value otherwise.
func (o *ForecastRequestV1) GetHardHorizon() int32 {
	if o == nil || IsNil(o.HardHorizon) {
		var ret int32
		return ret
	}
	return *o.HardHorizon
}

// GetHardHorizonOk returns a tuple with the HardHorizon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastRequestV1) GetHardHorizonOk() (*int32, bool) {
	if o == nil || IsNil(o.HardHorizon) {
		return nil, false
	}
	return o.HardHorizon, true
}

// HasHardHorizon returns a boolean if a field has been set.
func (o *ForecastRequestV1) HasHardHorizon() bool {
	if o != nil && !IsNil(o.HardHorizon) {
		return true
	}

	return false
}

// SetHardHorizon gets a reference to the given int32 and assigns it to the HardHorizon field.
func (o *ForecastRequestV1) SetHardHorizon(v int32) {
	o.HardHorizon = &v
}

// GetPipelineVersion returns the PipelineVersion field value
func (o *ForecastRequestV1) GetPipelineVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PipelineVersion
}

// GetPipelineVersionOk returns a tuple with the PipelineVersion field value
// and a boolean to check if the value has been set.
func (o *ForecastRequestV1) GetPipelineVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PipelineVersion, true
}

// SetPipelineVersion sets field value
func (o *ForecastRequestV1) SetPipelineVersion(v string) {
	o.PipelineVersion = v
}

// GetRecencyFactor returns the RecencyFactor field value
func (o *ForecastRequestV1) GetRecencyFactor() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.RecencyFactor
}

// GetRecencyFactorOk returns a tuple with the RecencyFactor field value
// and a boolean to check if the value has been set.
func (o *ForecastRequestV1) GetRecencyFactorOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecencyFactor, true
}

// SetRecencyFactor sets field value
func (o *ForecastRequestV1) SetRecencyFactor(v float64) {
	o.RecencyFactor = v
}

// GetSoftHorizon returns the SoftHorizon field value if set, zero value otherwise.
func (o *ForecastRequestV1) GetSoftHorizon() int32 {
	if o == nil || IsNil(o.SoftHorizon) {
		var ret int32
		return ret
	}
	return *o.SoftHorizon
}

// GetSoftHorizonOk returns a tuple with the SoftHorizon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastRequestV1) GetSoftHorizonOk() (*int32, bool) {
	if o == nil || IsNil(o.SoftHorizon) {
		return nil, false
	}
	return o.SoftHorizon, true
}

// HasSoftHorizon returns a boolean if a field has been set.
func (o *ForecastRequestV1) HasSoftHorizon() bool {
	if o != nil && !IsNil(o.SoftHorizon) {
		return true
	}

	return false
}

// SetSoftHorizon gets a reference to the given int32 and assigns it to the SoftHorizon field.
func (o *ForecastRequestV1) SetSoftHorizon(v int32) {
	o.SoftHorizon = &v
}

// GetStrictlyPositive returns the StrictlyPositive field value if set, zero value otherwise.
func (o *ForecastRequestV1) GetStrictlyPositive() bool {
	if o == nil || IsNil(o.StrictlyPositive) {
		var ret bool
		return ret
	}
	return *o.StrictlyPositive
}

// GetStrictlyPositiveOk returns a tuple with the StrictlyPositive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastRequestV1) GetStrictlyPositiveOk() (*bool, bool) {
	if o == nil || IsNil(o.StrictlyPositive) {
		return nil, false
	}
	return o.StrictlyPositive, true
}

// HasStrictlyPositive returns a boolean if a field has been set.
func (o *ForecastRequestV1) HasStrictlyPositive() bool {
	if o != nil && !IsNil(o.StrictlyPositive) {
		return true
	}

	return false
}

// SetStrictlyPositive gets a reference to the given bool and assigns it to the StrictlyPositive field.
func (o *ForecastRequestV1) SetStrictlyPositive(v bool) {
	o.StrictlyPositive = &v
}

// GetTimeseries returns the Timeseries field value
func (o *ForecastRequestV1) GetTimeseries() map[string]float32 {
	if o == nil {
		var ret map[string]float32
		return ret
	}

	return o.Timeseries
}

// GetTimeseriesOk returns a tuple with the Timeseries field value
// and a boolean to check if the value has been set.
func (o *ForecastRequestV1) GetTimeseriesOk() (*map[string]float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timeseries, true
}

// SetTimeseries sets field value
func (o *ForecastRequestV1) SetTimeseries(v map[string]float32) {
	o.Timeseries = v
}

// GetTimeseriesMetadata returns the TimeseriesMetadata field value
func (o *ForecastRequestV1) GetTimeseriesMetadata() TimeseriesMetadata {
	if o == nil {
		var ret TimeseriesMetadata
		return ret
	}

	return o.TimeseriesMetadata
}

// GetTimeseriesMetadataOk returns a tuple with the TimeseriesMetadata field value
// and a boolean to check if the value has been set.
func (o *ForecastRequestV1) GetTimeseriesMetadataOk() (*TimeseriesMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeseriesMetadata, true
}

// SetTimeseriesMetadata sets field value
func (o *ForecastRequestV1) SetTimeseriesMetadata(v TimeseriesMetadata) {
	o.TimeseriesMetadata = v
}

func (o ForecastRequestV1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ForecastRequestV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Backtest) {
		toSerialize["backtest"] = o.Backtest
	}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	toSerialize["frequency"] = o.Frequency
	if !IsNil(o.HardHorizon) {
		toSerialize["hard_horizon"] = o.HardHorizon
	}
	toSerialize["pipeline_version"] = o.PipelineVersion
	toSerialize["recency_factor"] = o.RecencyFactor
	if !IsNil(o.SoftHorizon) {
		toSerialize["soft_horizon"] = o.SoftHorizon
	}
	if !IsNil(o.StrictlyPositive) {
		toSerialize["strictly_positive"] = o.StrictlyPositive
	}
	toSerialize["timeseries"] = o.Timeseries
	toSerialize["timeseries_metadata"] = o.TimeseriesMetadata
	return toSerialize, nil
}

func (o *ForecastRequestV1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"frequency",
		"pipeline_version",
		"recency_factor",
		"timeseries",
		"timeseries_metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varForecastRequestV1 := _ForecastRequestV1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varForecastRequestV1)

	if err != nil {
		return err
	}

	*o = ForecastRequestV1(varForecastRequestV1)

	return err
}

type NullableForecastRequestV1 struct {
	value *ForecastRequestV1
	isSet bool
}

func (v NullableForecastRequestV1) Get() *ForecastRequestV1 {
	return v.value
}

func (v *NullableForecastRequestV1) Set(val *ForecastRequestV1) {
	v.value = val
	v.isSet = true
}

func (v NullableForecastRequestV1) IsSet() bool {
	return v.isSet
}

func (v *NullableForecastRequestV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForecastRequestV1(val *ForecastRequestV1) *NullableForecastRequestV1 {
	return &NullableForecastRequestV1{value: val, isSet: true}
}

func (v NullableForecastRequestV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForecastRequestV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


