/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
)

// checks if the HealthGet503ResponseComponentsValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthGet503ResponseComponentsValue{}

// HealthGet503ResponseComponentsValue struct for HealthGet503ResponseComponentsValue
type HealthGet503ResponseComponentsValue struct {
	Status *string `json:"status,omitempty"`
}

// NewHealthGet503ResponseComponentsValue instantiates a new HealthGet503ResponseComponentsValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthGet503ResponseComponentsValue() *HealthGet503ResponseComponentsValue {
	this := HealthGet503ResponseComponentsValue{}
	return &this
}

// NewHealthGet503ResponseComponentsValueWithDefaults instantiates a new HealthGet503ResponseComponentsValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthGet503ResponseComponentsValueWithDefaults() *HealthGet503ResponseComponentsValue {
	this := HealthGet503ResponseComponentsValue{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *HealthGet503ResponseComponentsValue) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthGet503ResponseComponentsValue) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *HealthGet503ResponseComponentsValue) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *HealthGet503ResponseComponentsValue) SetStatus(v string) {
	o.Status = &v
}

func (o HealthGet503ResponseComponentsValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthGet503ResponseComponentsValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableHealthGet503ResponseComponentsValue struct {
	value *HealthGet503ResponseComponentsValue
	isSet bool
}

func (v NullableHealthGet503ResponseComponentsValue) Get() *HealthGet503ResponseComponentsValue {
	return v.value
}

func (v *NullableHealthGet503ResponseComponentsValue) Set(val *HealthGet503ResponseComponentsValue) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthGet503ResponseComponentsValue) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthGet503ResponseComponentsValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthGet503ResponseComponentsValue(val *HealthGet503ResponseComponentsValue) *NullableHealthGet503ResponseComponentsValue {
	return &NullableHealthGet503ResponseComponentsValue{value: val, isSet: true}
}

func (v NullableHealthGet503ResponseComponentsValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthGet503ResponseComponentsValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


