/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the EuroTranche type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EuroTranche{}

// EuroTranche A time-limited credit allocation. Multiple tranches can be active simultaneously; the system consumes the one expiring soonest first. 
type EuroTranche struct {
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	Id string `json:"id"`
	// Original size of this tranche in EUR cents.
	InitialEurCents int64 `json:"initial_eur_cents"`
	// Unconsumed balance remaining in this tranche, in EUR cents.
	RemainingEurCents int64 `json:"remaining_eur_cents"`
	// Origin of the tranche — one of `signup_trial`, `stripe`, `partner`, `legacy`. Other labels may appear for custom grants.
	Source string `json:"source"`
}

type _EuroTranche EuroTranche

// NewEuroTranche instantiates a new EuroTranche object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEuroTranche(createdAt time.Time, expiresAt time.Time, id string, initialEurCents int64, remainingEurCents int64, source string) *EuroTranche {
	this := EuroTranche{}
	this.CreatedAt = createdAt
	this.ExpiresAt = expiresAt
	this.Id = id
	this.InitialEurCents = initialEurCents
	this.RemainingEurCents = remainingEurCents
	this.Source = source
	return &this
}

// NewEuroTrancheWithDefaults instantiates a new EuroTranche object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEuroTrancheWithDefaults() *EuroTranche {
	this := EuroTranche{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *EuroTranche) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *EuroTranche) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *EuroTranche) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *EuroTranche) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *EuroTranche) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *EuroTranche) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetId returns the Id field value
func (o *EuroTranche) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EuroTranche) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EuroTranche) SetId(v string) {
	o.Id = v
}

// GetInitialEurCents returns the InitialEurCents field value
func (o *EuroTranche) GetInitialEurCents() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.InitialEurCents
}

// GetInitialEurCentsOk returns a tuple with the InitialEurCents field value
// and a boolean to check if the value has been set.
func (o *EuroTranche) GetInitialEurCentsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InitialEurCents, true
}

// SetInitialEurCents sets field value
func (o *EuroTranche) SetInitialEurCents(v int64) {
	o.InitialEurCents = v
}

// GetRemainingEurCents returns the RemainingEurCents field value
func (o *EuroTranche) GetRemainingEurCents() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RemainingEurCents
}

// GetRemainingEurCentsOk returns a tuple with the RemainingEurCents field value
// and a boolean to check if the value has been set.
func (o *EuroTranche) GetRemainingEurCentsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemainingEurCents, true
}

// SetRemainingEurCents sets field value
func (o *EuroTranche) SetRemainingEurCents(v int64) {
	o.RemainingEurCents = v
}

// GetSource returns the Source field value
func (o *EuroTranche) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *EuroTranche) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *EuroTranche) SetSource(v string) {
	o.Source = v
}

func (o EuroTranche) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EuroTranche) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["expires_at"] = o.ExpiresAt
	toSerialize["id"] = o.Id
	toSerialize["initial_eur_cents"] = o.InitialEurCents
	toSerialize["remaining_eur_cents"] = o.RemainingEurCents
	toSerialize["source"] = o.Source
	return toSerialize, nil
}

func (o *EuroTranche) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"expires_at",
		"id",
		"initial_eur_cents",
		"remaining_eur_cents",
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEuroTranche := _EuroTranche{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEuroTranche)

	if err != nil {
		return err
	}

	*o = EuroTranche(varEuroTranche)

	return err
}

type NullableEuroTranche struct {
	value *EuroTranche
	isSet bool
}

func (v NullableEuroTranche) Get() *EuroTranche {
	return v.value
}

func (v *NullableEuroTranche) Set(val *EuroTranche) {
	v.value = val
	v.isSet = true
}

func (v NullableEuroTranche) IsSet() bool {
	return v.isSet
}

func (v *NullableEuroTranche) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEuroTranche(val *EuroTranche) *NullableEuroTranche {
	return &NullableEuroTranche{value: val, isSet: true}
}

func (v NullableEuroTranche) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEuroTranche) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


