/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsageEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageEvent{}

// UsageEvent A single billing charge, corresponding to one API call or one completed async job.
type UsageEvent struct {
	// The `async_jobs.id` (UUID) for async pipeline charges; null for synchronous endpoint charges.
	AsyncJobId NullableString `json:"async_job_id,omitempty"`
	// Timestamp of the charge (ISO 8601).
	CreatedAt string `json:"created_at"`
	// Whole credits debited for this row before EUR conversion.
	CreditsCharged int64 `json:"credits_charged"`
	// Billing route key (e.g. `drivers`, `alerts`, or a forecast pipeline type).
	Endpoint *string `json:"endpoint,omitempty"`
	// EUR cents debited for this row (1 EUR = 100 cents).
	EurCentsCharged int64 `json:"eur_cents_charged"`
	// Auto-increment row identifier.
	Id int64 `json:"id"`
	// Metered quantity — item count for per-unit pricing, 1 for flat-fee strategies.
	Units int64 `json:"units"`
}

type _UsageEvent UsageEvent

// NewUsageEvent instantiates a new UsageEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageEvent(createdAt string, creditsCharged int64, eurCentsCharged int64, id int64, units int64) *UsageEvent {
	this := UsageEvent{}
	this.CreatedAt = createdAt
	this.CreditsCharged = creditsCharged
	this.EurCentsCharged = eurCentsCharged
	this.Id = id
	this.Units = units
	return &this
}

// NewUsageEventWithDefaults instantiates a new UsageEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageEventWithDefaults() *UsageEvent {
	this := UsageEvent{}
	return &this
}

// GetAsyncJobId returns the AsyncJobId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UsageEvent) GetAsyncJobId() string {
	if o == nil || IsNil(o.AsyncJobId.Get()) {
		var ret string
		return ret
	}
	return *o.AsyncJobId.Get()
}

// GetAsyncJobIdOk returns a tuple with the AsyncJobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UsageEvent) GetAsyncJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AsyncJobId.Get(), o.AsyncJobId.IsSet()
}

// HasAsyncJobId returns a boolean if a field has been set.
func (o *UsageEvent) HasAsyncJobId() bool {
	if o != nil && o.AsyncJobId.IsSet() {
		return true
	}

	return false
}

// SetAsyncJobId gets a reference to the given NullableString and assigns it to the AsyncJobId field.
func (o *UsageEvent) SetAsyncJobId(v string) {
	o.AsyncJobId.Set(&v)
}
// SetAsyncJobIdNil sets the value for AsyncJobId to be an explicit nil
func (o *UsageEvent) SetAsyncJobIdNil() {
	o.AsyncJobId.Set(nil)
}

// UnsetAsyncJobId ensures that no value is present for AsyncJobId, not even an explicit nil
func (o *UsageEvent) UnsetAsyncJobId() {
	o.AsyncJobId.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *UsageEvent) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *UsageEvent) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *UsageEvent) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetCreditsCharged returns the CreditsCharged field value
func (o *UsageEvent) GetCreditsCharged() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreditsCharged
}

// GetCreditsChargedOk returns a tuple with the CreditsCharged field value
// and a boolean to check if the value has been set.
func (o *UsageEvent) GetCreditsChargedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreditsCharged, true
}

// SetCreditsCharged sets field value
func (o *UsageEvent) SetCreditsCharged(v int64) {
	o.CreditsCharged = v
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise.
func (o *UsageEvent) GetEndpoint() string {
	if o == nil || IsNil(o.Endpoint) {
		var ret string
		return ret
	}
	return *o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsageEvent) GetEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.Endpoint) {
		return nil, false
	}
	return o.Endpoint, true
}

// HasEndpoint returns a boolean if a field has been set.
func (o *UsageEvent) HasEndpoint() bool {
	if o != nil && !IsNil(o.Endpoint) {
		return true
	}

	return false
}

// SetEndpoint gets a reference to the given string and assigns it to the Endpoint field.
func (o *UsageEvent) SetEndpoint(v string) {
	o.Endpoint = &v
}

// GetEurCentsCharged returns the EurCentsCharged field value
func (o *UsageEvent) GetEurCentsCharged() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.EurCentsCharged
}

// GetEurCentsChargedOk returns a tuple with the EurCentsCharged field value
// and a boolean to check if the value has been set.
func (o *UsageEvent) GetEurCentsChargedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EurCentsCharged, true
}

// SetEurCentsCharged sets field value
func (o *UsageEvent) SetEurCentsCharged(v int64) {
	o.EurCentsCharged = v
}

// GetId returns the Id field value
func (o *UsageEvent) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UsageEvent) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UsageEvent) SetId(v int64) {
	o.Id = v
}

// GetUnits returns the Units field value
func (o *UsageEvent) GetUnits() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Units
}

// GetUnitsOk returns a tuple with the Units field value
// and a boolean to check if the value has been set.
func (o *UsageEvent) GetUnitsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Units, true
}

// SetUnits sets field value
func (o *UsageEvent) SetUnits(v int64) {
	o.Units = v
}

func (o UsageEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AsyncJobId.IsSet() {
		toSerialize["async_job_id"] = o.AsyncJobId.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["credits_charged"] = o.CreditsCharged
	if !IsNil(o.Endpoint) {
		toSerialize["endpoint"] = o.Endpoint
	}
	toSerialize["eur_cents_charged"] = o.EurCentsCharged
	toSerialize["id"] = o.Id
	toSerialize["units"] = o.Units
	return toSerialize, nil
}

func (o *UsageEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"credits_charged",
		"eur_cents_charged",
		"id",
		"units",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsageEvent := _UsageEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsageEvent)

	if err != nil {
		return err
	}

	*o = UsageEvent(varUsageEvent)

	return err
}

type NullableUsageEvent struct {
	value *UsageEvent
	isSet bool
}

func (v NullableUsageEvent) Get() *UsageEvent {
	return v.value
}

func (v *NullableUsageEvent) Set(val *UsageEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageEvent(val *UsageEvent) *NullableUsageEvent {
	return &NullableUsageEvent{value: val, isSet: true}
}

func (v NullableUsageEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


