/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TimeseriesMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TimeseriesMetadata{}

// TimeseriesMetadata Descriptive metadata the ranking model uses to interpret and contextualize the timeseries.
type TimeseriesMetadata struct {
	// Extended context for the model, up to 2048 characters. More detail improves driver relevance.
	Description *string `json:"description,omitempty"`
	// Up to 20 semantic tags that help anchor the search to relevant datasets.
	Keywords []string `json:"keywords,omitempty"`
	// Short identifier for the series, 20–511 characters.
	Title string `json:"title"`
}

type _TimeseriesMetadata TimeseriesMetadata

// NewTimeseriesMetadata instantiates a new TimeseriesMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimeseriesMetadata(title string) *TimeseriesMetadata {
	this := TimeseriesMetadata{}
	this.Title = title
	return &this
}

// NewTimeseriesMetadataWithDefaults instantiates a new TimeseriesMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimeseriesMetadataWithDefaults() *TimeseriesMetadata {
	this := TimeseriesMetadata{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *TimeseriesMetadata) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeseriesMetadata) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *TimeseriesMetadata) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *TimeseriesMetadata) SetDescription(v string) {
	o.Description = &v
}

// GetKeywords returns the Keywords field value if set, zero value otherwise.
func (o *TimeseriesMetadata) GetKeywords() []string {
	if o == nil || IsNil(o.Keywords) {
		var ret []string
		return ret
	}
	return o.Keywords
}

// GetKeywordsOk returns a tuple with the Keywords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TimeseriesMetadata) GetKeywordsOk() ([]string, bool) {
	if o == nil || IsNil(o.Keywords) {
		return nil, false
	}
	return o.Keywords, true
}

// HasKeywords returns a boolean if a field has been set.
func (o *TimeseriesMetadata) HasKeywords() bool {
	if o != nil && !IsNil(o.Keywords) {
		return true
	}

	return false
}

// SetKeywords gets a reference to the given []string and assigns it to the Keywords field.
func (o *TimeseriesMetadata) SetKeywords(v []string) {
	o.Keywords = v
}

// GetTitle returns the Title field value
func (o *TimeseriesMetadata) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *TimeseriesMetadata) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *TimeseriesMetadata) SetTitle(v string) {
	o.Title = v
}

func (o TimeseriesMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TimeseriesMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Keywords) {
		toSerialize["keywords"] = o.Keywords
	}
	toSerialize["title"] = o.Title
	return toSerialize, nil
}

func (o *TimeseriesMetadata) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTimeseriesMetadata := _TimeseriesMetadata{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTimeseriesMetadata)

	if err != nil {
		return err
	}

	*o = TimeseriesMetadata(varTimeseriesMetadata)

	return err
}

type NullableTimeseriesMetadata struct {
	value *TimeseriesMetadata
	isSet bool
}

func (v NullableTimeseriesMetadata) Get() *TimeseriesMetadata {
	return v.value
}

func (v *NullableTimeseriesMetadata) Set(val *TimeseriesMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableTimeseriesMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableTimeseriesMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimeseriesMetadata(val *TimeseriesMetadata) *NullableTimeseriesMetadata {
	return &NullableTimeseriesMetadata{value: val, isSet: true}
}

func (v NullableTimeseriesMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimeseriesMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


