/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AlertsRequestV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlertsRequestV1{}

// AlertsRequestV1 Body of `POST /api/v1/alerts`.  `filters.limit` controls how many alerts are returned (default **100**, max **1000**). `date_from` / `date_to` are optional date bounds (YYYY-MM-DD). 
type AlertsRequestV1 struct {
	// When true, treat the supplied metadata as already context-enriched.
	ContextEnriched bool `json:"context_enriched"`
	// Optional start date bound for alert detection (YYYY-MM-DD).
	DateFrom *string `json:"date_from,omitempty"`
	// Optional end date bound for alert detection (YYYY-MM-DD).
	DateTo *string `json:"date_to,omitempty"`
	// Optional. `limit` controls the number of alerts returned (**0–1000**, default **100**). `categories[]` and `regions[]` narrow the alert universe; each must be an integer **1–9999**. Values are not verified against catalog APIs. 
	Filters *Filters `json:"filters,omitempty"`
	Metadata TimeseriesMetadata `json:"metadata"`
}

type _AlertsRequestV1 AlertsRequestV1

// NewAlertsRequestV1 instantiates a new AlertsRequestV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertsRequestV1(contextEnriched bool, metadata TimeseriesMetadata) *AlertsRequestV1 {
	this := AlertsRequestV1{}
	this.ContextEnriched = contextEnriched
	this.Metadata = metadata
	return &this
}

// NewAlertsRequestV1WithDefaults instantiates a new AlertsRequestV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertsRequestV1WithDefaults() *AlertsRequestV1 {
	this := AlertsRequestV1{}
	return &this
}

// GetContextEnriched returns the ContextEnriched field value
func (o *AlertsRequestV1) GetContextEnriched() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ContextEnriched
}

// GetContextEnrichedOk returns a tuple with the ContextEnriched field value
// and a boolean to check if the value has been set.
func (o *AlertsRequestV1) GetContextEnrichedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContextEnriched, true
}

// SetContextEnriched sets field value
func (o *AlertsRequestV1) SetContextEnriched(v bool) {
	o.ContextEnriched = v
}

// GetDateFrom returns the DateFrom field value if set, zero value otherwise.
func (o *AlertsRequestV1) GetDateFrom() string {
	if o == nil || IsNil(o.DateFrom) {
		var ret string
		return ret
	}
	return *o.DateFrom
}

// GetDateFromOk returns a tuple with the DateFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertsRequestV1) GetDateFromOk() (*string, bool) {
	if o == nil || IsNil(o.DateFrom) {
		return nil, false
	}
	return o.DateFrom, true
}

// HasDateFrom returns a boolean if a field has been set.
func (o *AlertsRequestV1) HasDateFrom() bool {
	if o != nil && !IsNil(o.DateFrom) {
		return true
	}

	return false
}

// SetDateFrom gets a reference to the given string and assigns it to the DateFrom field.
func (o *AlertsRequestV1) SetDateFrom(v string) {
	o.DateFrom = &v
}

// GetDateTo returns the DateTo field value if set, zero value otherwise.
func (o *AlertsRequestV1) GetDateTo() string {
	if o == nil || IsNil(o.DateTo) {
		var ret string
		return ret
	}
	return *o.DateTo
}

// GetDateToOk returns a tuple with the DateTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertsRequestV1) GetDateToOk() (*string, bool) {
	if o == nil || IsNil(o.DateTo) {
		return nil, false
	}
	return o.DateTo, true
}

// HasDateTo returns a boolean if a field has been set.
func (o *AlertsRequestV1) HasDateTo() bool {
	if o != nil && !IsNil(o.DateTo) {
		return true
	}

	return false
}

// SetDateTo gets a reference to the given string and assigns it to the DateTo field.
func (o *AlertsRequestV1) SetDateTo(v string) {
	o.DateTo = &v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *AlertsRequestV1) GetFilters() Filters {
	if o == nil || IsNil(o.Filters) {
		var ret Filters
		return ret
	}
	return *o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertsRequestV1) GetFiltersOk() (*Filters, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *AlertsRequestV1) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given Filters and assigns it to the Filters field.
func (o *AlertsRequestV1) SetFilters(v Filters) {
	o.Filters = &v
}

// GetMetadata returns the Metadata field value
func (o *AlertsRequestV1) GetMetadata() TimeseriesMetadata {
	if o == nil {
		var ret TimeseriesMetadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *AlertsRequestV1) GetMetadataOk() (*TimeseriesMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *AlertsRequestV1) SetMetadata(v TimeseriesMetadata) {
	o.Metadata = v
}

func (o AlertsRequestV1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlertsRequestV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["context_enriched"] = o.ContextEnriched
	if !IsNil(o.DateFrom) {
		toSerialize["date_from"] = o.DateFrom
	}
	if !IsNil(o.DateTo) {
		toSerialize["date_to"] = o.DateTo
	}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	toSerialize["metadata"] = o.Metadata
	return toSerialize, nil
}

func (o *AlertsRequestV1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"context_enriched",
		"metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAlertsRequestV1 := _AlertsRequestV1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAlertsRequestV1)

	if err != nil {
		return err
	}

	*o = AlertsRequestV1(varAlertsRequestV1)

	return err
}

type NullableAlertsRequestV1 struct {
	value *AlertsRequestV1
	isSet bool
}

func (v NullableAlertsRequestV1) Get() *AlertsRequestV1 {
	return v.value
}

func (v *NullableAlertsRequestV1) Set(val *AlertsRequestV1) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertsRequestV1) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertsRequestV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertsRequestV1(val *AlertsRequestV1) *NullableAlertsRequestV1 {
	return &NullableAlertsRequestV1{value: val, isSet: true}
}

func (v NullableAlertsRequestV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertsRequestV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


