/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobsPagination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobsPagination{}

// JobsPagination struct for JobsPagination
type JobsPagination struct {
	// Page size echoed back from the request.
	Limit int32 `json:"limit"`
	// Sort direction echoed back from the request.
	Order string `json:"order"`
	// 1-indexed current page number echoed back from the request.
	Page int32 `json:"page"`
	// Column the rows are sorted by, echoed back from the request.
	Sort string `json:"sort"`
	// Total matching rows for the authenticated user (full set, not just this page).
	Total int64 `json:"total"`
	// ceil(total / limit). Zero when total is zero.
	TotalPages int64 `json:"total_pages"`
}

type _JobsPagination JobsPagination

// NewJobsPagination instantiates a new JobsPagination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobsPagination(limit int32, order string, page int32, sort string, total int64, totalPages int64) *JobsPagination {
	this := JobsPagination{}
	this.Limit = limit
	this.Order = order
	this.Page = page
	this.Sort = sort
	this.Total = total
	this.TotalPages = totalPages
	return &this
}

// NewJobsPaginationWithDefaults instantiates a new JobsPagination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobsPaginationWithDefaults() *JobsPagination {
	this := JobsPagination{}
	return &this
}

// GetLimit returns the Limit field value
func (o *JobsPagination) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *JobsPagination) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *JobsPagination) SetLimit(v int32) {
	o.Limit = v
}

// GetOrder returns the Order field value
func (o *JobsPagination) GetOrder() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Order
}

// GetOrderOk returns a tuple with the Order field value
// and a boolean to check if the value has been set.
func (o *JobsPagination) GetOrderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Order, true
}

// SetOrder sets field value
func (o *JobsPagination) SetOrder(v string) {
	o.Order = v
}

// GetPage returns the Page field value
func (o *JobsPagination) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *JobsPagination) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *JobsPagination) SetPage(v int32) {
	o.Page = v
}

// GetSort returns the Sort field value
func (o *JobsPagination) GetSort() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sort
}

// GetSortOk returns a tuple with the Sort field value
// and a boolean to check if the value has been set.
func (o *JobsPagination) GetSortOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sort, true
}

// SetSort sets field value
func (o *JobsPagination) SetSort(v string) {
	o.Sort = v
}

// GetTotal returns the Total field value
func (o *JobsPagination) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *JobsPagination) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *JobsPagination) SetTotal(v int64) {
	o.Total = v
}

// GetTotalPages returns the TotalPages field value
func (o *JobsPagination) GetTotalPages() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value
// and a boolean to check if the value has been set.
func (o *JobsPagination) GetTotalPagesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalPages, true
}

// SetTotalPages sets field value
func (o *JobsPagination) SetTotalPages(v int64) {
	o.TotalPages = v
}

func (o JobsPagination) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobsPagination) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["limit"] = o.Limit
	toSerialize["order"] = o.Order
	toSerialize["page"] = o.Page
	toSerialize["sort"] = o.Sort
	toSerialize["total"] = o.Total
	toSerialize["total_pages"] = o.TotalPages
	return toSerialize, nil
}

func (o *JobsPagination) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"limit",
		"order",
		"page",
		"sort",
		"total",
		"total_pages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobsPagination := _JobsPagination{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobsPagination)

	if err != nil {
		return err
	}

	*o = JobsPagination(varJobsPagination)

	return err
}

type NullableJobsPagination struct {
	value *JobsPagination
	isSet bool
}

func (v NullableJobsPagination) Get() *JobsPagination {
	return v.value
}

func (v *NullableJobsPagination) Set(val *JobsPagination) {
	v.value = val
	v.isSet = true
}

func (v NullableJobsPagination) IsSet() bool {
	return v.isSet
}

func (v *NullableJobsPagination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobsPagination(val *JobsPagination) *NullableJobsPagination {
	return &NullableJobsPagination{value: val, isSet: true}
}

func (v NullableJobsPagination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobsPagination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


