/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
)

// checks if the Filters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Filters{}

// Filters Optional narrowing for forecast, drivers, and alerts requests. Category and region ids must fall in **1–9999**. Discover valid ids via `GET /api/v1/regions` and `GET /api/v1/categories` — submitted ids are not cross-checked on submit. 
type Filters struct {
	// Thematic category ids to filter by; each must be an integer **1–9999** inclusive.
	Categories []int32 `json:"categories,omitempty"`
	// Maximum number of items to return. When omitted, a per-environment default is applied (100 by default). The maximum accepted value is operator-configurable (default 1000).
	Limit *int32 `json:"limit,omitempty"`
	// Geographic region ids to filter by; each must be an integer **1–9999** inclusive.
	Regions []int32 `json:"regions,omitempty"`
}

// NewFilters instantiates a new Filters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilters() *Filters {
	this := Filters{}
	return &this
}

// NewFiltersWithDefaults instantiates a new Filters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFiltersWithDefaults() *Filters {
	this := Filters{}
	return &this
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *Filters) GetCategories() []int32 {
	if o == nil || IsNil(o.Categories) {
		var ret []int32
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Filters) GetCategoriesOk() ([]int32, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *Filters) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []int32 and assigns it to the Categories field.
func (o *Filters) SetCategories(v []int32) {
	o.Categories = v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *Filters) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Filters) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *Filters) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *Filters) SetLimit(v int32) {
	o.Limit = &v
}

// GetRegions returns the Regions field value if set, zero value otherwise.
func (o *Filters) GetRegions() []int32 {
	if o == nil || IsNil(o.Regions) {
		var ret []int32
		return ret
	}
	return o.Regions
}

// GetRegionsOk returns a tuple with the Regions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Filters) GetRegionsOk() ([]int32, bool) {
	if o == nil || IsNil(o.Regions) {
		return nil, false
	}
	return o.Regions, true
}

// HasRegions returns a boolean if a field has been set.
func (o *Filters) HasRegions() bool {
	if o != nil && !IsNil(o.Regions) {
		return true
	}

	return false
}

// SetRegions gets a reference to the given []int32 and assigns it to the Regions field.
func (o *Filters) SetRegions(v []int32) {
	o.Regions = v
}

func (o Filters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Filters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Regions) {
		toSerialize["regions"] = o.Regions
	}
	return toSerialize, nil
}

type NullableFilters struct {
	value *Filters
	isSet bool
}

func (v NullableFilters) Get() *Filters {
	return v.value
}

func (v *NullableFilters) Set(val *Filters) {
	v.value = val
	v.isSet = true
}

func (v NullableFilters) IsSet() bool {
	return v.isSet
}

func (v *NullableFilters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilters(val *Filters) *NullableFilters {
	return &NullableFilters{value: val, isSet: true}
}

func (v NullableFilters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


