/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
)

// checks if the ApiV1AlertsPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV1AlertsPost200Response{}

// ApiV1AlertsPost200Response struct for ApiV1AlertsPost200Response
type ApiV1AlertsPost200Response struct {
	Alerts []AlertItemV1 `json:"alerts,omitempty"`
}

// NewApiV1AlertsPost200Response instantiates a new ApiV1AlertsPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1AlertsPost200Response() *ApiV1AlertsPost200Response {
	this := ApiV1AlertsPost200Response{}
	return &this
}

// NewApiV1AlertsPost200ResponseWithDefaults instantiates a new ApiV1AlertsPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1AlertsPost200ResponseWithDefaults() *ApiV1AlertsPost200Response {
	this := ApiV1AlertsPost200Response{}
	return &this
}

// GetAlerts returns the Alerts field value if set, zero value otherwise.
func (o *ApiV1AlertsPost200Response) GetAlerts() []AlertItemV1 {
	if o == nil || IsNil(o.Alerts) {
		var ret []AlertItemV1
		return ret
	}
	return o.Alerts
}

// GetAlertsOk returns a tuple with the Alerts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1AlertsPost200Response) GetAlertsOk() ([]AlertItemV1, bool) {
	if o == nil || IsNil(o.Alerts) {
		return nil, false
	}
	return o.Alerts, true
}

// HasAlerts returns a boolean if a field has been set.
func (o *ApiV1AlertsPost200Response) HasAlerts() bool {
	if o != nil && !IsNil(o.Alerts) {
		return true
	}

	return false
}

// SetAlerts gets a reference to the given []AlertItemV1 and assigns it to the Alerts field.
func (o *ApiV1AlertsPost200Response) SetAlerts(v []AlertItemV1) {
	o.Alerts = v
}

func (o ApiV1AlertsPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV1AlertsPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Alerts) {
		toSerialize["alerts"] = o.Alerts
	}
	return toSerialize, nil
}

type NullableApiV1AlertsPost200Response struct {
	value *ApiV1AlertsPost200Response
	isSet bool
}

func (v NullableApiV1AlertsPost200Response) Get() *ApiV1AlertsPost200Response {
	return v.value
}

func (v *NullableApiV1AlertsPost200Response) Set(val *ApiV1AlertsPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1AlertsPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1AlertsPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1AlertsPost200Response(val *ApiV1AlertsPost200Response) *NullableApiV1AlertsPost200Response {
	return &NullableApiV1AlertsPost200Response{value: val, isSet: true}
}

func (v NullableApiV1AlertsPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1AlertsPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


