/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
	"fmt"
)

// checks if the RegionItemV1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegionItemV1{}

// RegionItemV1 A single geographic region returned by GET /api/v1/regions.
type RegionItemV1 struct {
	// Integer identifier. Use this value in filters.regions[].
	Id int32 `json:"id"`
	// Geographic latitude (0.0 when not applicable).
	Latitude *float64 `json:"latitude,omitempty"`
	// Geographic longitude (0.0 when not applicable).
	Longitude *float64 `json:"longitude,omitempty"`
	// Human-readable region label.
	Name string `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _RegionItemV1 RegionItemV1

// NewRegionItemV1 instantiates a new RegionItemV1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegionItemV1(id int32, name string) *RegionItemV1 {
	this := RegionItemV1{}
	this.Id = id
	var latitude float64 = 0.0
	this.Latitude = &latitude
	var longitude float64 = 0.0
	this.Longitude = &longitude
	this.Name = name
	return &this
}

// NewRegionItemV1WithDefaults instantiates a new RegionItemV1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegionItemV1WithDefaults() *RegionItemV1 {
	this := RegionItemV1{}
	var latitude float64 = 0.0
	this.Latitude = &latitude
	var longitude float64 = 0.0
	this.Longitude = &longitude
	return &this
}

// GetId returns the Id field value
func (o *RegionItemV1) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RegionItemV1) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RegionItemV1) SetId(v int32) {
	o.Id = v
}

// GetLatitude returns the Latitude field value if set, zero value otherwise.
func (o *RegionItemV1) GetLatitude() float64 {
	if o == nil || IsNil(o.Latitude) {
		var ret float64
		return ret
	}
	return *o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegionItemV1) GetLatitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Latitude) {
		return nil, false
	}
	return o.Latitude, true
}

// HasLatitude returns a boolean if a field has been set.
func (o *RegionItemV1) HasLatitude() bool {
	if o != nil && !IsNil(o.Latitude) {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given float64 and assigns it to the Latitude field.
func (o *RegionItemV1) SetLatitude(v float64) {
	o.Latitude = &v
}

// GetLongitude returns the Longitude field value if set, zero value otherwise.
func (o *RegionItemV1) GetLongitude() float64 {
	if o == nil || IsNil(o.Longitude) {
		var ret float64
		return ret
	}
	return *o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegionItemV1) GetLongitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Longitude) {
		return nil, false
	}
	return o.Longitude, true
}

// HasLongitude returns a boolean if a field has been set.
func (o *RegionItemV1) HasLongitude() bool {
	if o != nil && !IsNil(o.Longitude) {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given float64 and assigns it to the Longitude field.
func (o *RegionItemV1) SetLongitude(v float64) {
	o.Longitude = &v
}

// GetName returns the Name field value
func (o *RegionItemV1) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RegionItemV1) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RegionItemV1) SetName(v string) {
	o.Name = v
}

func (o RegionItemV1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegionItemV1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Latitude) {
		toSerialize["latitude"] = o.Latitude
	}
	if !IsNil(o.Longitude) {
		toSerialize["longitude"] = o.Longitude
	}
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RegionItemV1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegionItemV1 := _RegionItemV1{}

	err = json.Unmarshal(data, &varRegionItemV1)

	if err != nil {
		return err
	}

	*o = RegionItemV1(varRegionItemV1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "latitude")
		delete(additionalProperties, "longitude")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRegionItemV1 struct {
	value *RegionItemV1
	isSet bool
}

func (v NullableRegionItemV1) Get() *RegionItemV1 {
	return v.value
}

func (v *NullableRegionItemV1) Set(val *RegionItemV1) {
	v.value = val
	v.isSet = true
}

func (v NullableRegionItemV1) IsSet() bool {
	return v.isSet
}

func (v *NullableRegionItemV1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegionItemV1(val *RegionItemV1) *NullableRegionItemV1 {
	return &NullableRegionItemV1{value: val, isSet: true}
}

func (v NullableRegionItemV1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegionItemV1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


