/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegionListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegionListResponse{}

// RegionListResponse struct for RegionListResponse
type RegionListResponse struct {
	// Complete region listing, sorted by id ascending. No pagination.
	Items []RegionItemV1 `json:"items"`
}

type _RegionListResponse RegionListResponse

// NewRegionListResponse instantiates a new RegionListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegionListResponse(items []RegionItemV1) *RegionListResponse {
	this := RegionListResponse{}
	this.Items = items
	return &this
}

// NewRegionListResponseWithDefaults instantiates a new RegionListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegionListResponseWithDefaults() *RegionListResponse {
	this := RegionListResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *RegionListResponse) GetItems() []RegionItemV1 {
	if o == nil {
		var ret []RegionItemV1
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *RegionListResponse) GetItemsOk() ([]RegionItemV1, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *RegionListResponse) SetItems(v []RegionItemV1) {
	o.Items = v
}

func (o RegionListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegionListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *RegionListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegionListResponse := _RegionListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegionListResponse)

	if err != nil {
		return err
	}

	*o = RegionListResponse(varRegionListResponse)

	return err
}

type NullableRegionListResponse struct {
	value *RegionListResponse
	isSet bool
}

func (v NullableRegionListResponse) Get() *RegionListResponse {
	return v.value
}

func (v *NullableRegionListResponse) Set(val *RegionListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRegionListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRegionListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegionListResponse(val *RegionListResponse) *NullableRegionListResponse {
	return &NullableRegionListResponse{value: val, isSet: true}
}

func (v NullableRegionListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegionListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


