/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
)

// checks if the HealthGet503Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthGet503Response{}

// HealthGet503Response struct for HealthGet503Response
type HealthGet503Response struct {
	Status *string `json:"status,omitempty"`
	Components *map[string]HealthGet503ResponseComponentsValue `json:"components,omitempty"`
}

// NewHealthGet503Response instantiates a new HealthGet503Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthGet503Response() *HealthGet503Response {
	this := HealthGet503Response{}
	return &this
}

// NewHealthGet503ResponseWithDefaults instantiates a new HealthGet503Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthGet503ResponseWithDefaults() *HealthGet503Response {
	this := HealthGet503Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *HealthGet503Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthGet503Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *HealthGet503Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *HealthGet503Response) SetStatus(v string) {
	o.Status = &v
}

// GetComponents returns the Components field value if set, zero value otherwise.
func (o *HealthGet503Response) GetComponents() map[string]HealthGet503ResponseComponentsValue {
	if o == nil || IsNil(o.Components) {
		var ret map[string]HealthGet503ResponseComponentsValue
		return ret
	}
	return *o.Components
}

// GetComponentsOk returns a tuple with the Components field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthGet503Response) GetComponentsOk() (*map[string]HealthGet503ResponseComponentsValue, bool) {
	if o == nil || IsNil(o.Components) {
		return nil, false
	}
	return o.Components, true
}

// HasComponents returns a boolean if a field has been set.
func (o *HealthGet503Response) HasComponents() bool {
	if o != nil && !IsNil(o.Components) {
		return true
	}

	return false
}

// SetComponents gets a reference to the given map[string]HealthGet503ResponseComponentsValue and assigns it to the Components field.
func (o *HealthGet503Response) SetComponents(v map[string]HealthGet503ResponseComponentsValue) {
	o.Components = &v
}

func (o HealthGet503Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthGet503Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Components) {
		toSerialize["components"] = o.Components
	}
	return toSerialize, nil
}

type NullableHealthGet503Response struct {
	value *HealthGet503Response
	isSet bool
}

func (v NullableHealthGet503Response) Get() *HealthGet503Response {
	return v.value
}

func (v *NullableHealthGet503Response) Set(val *HealthGet503Response) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthGet503Response) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthGet503Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthGet503Response(val *HealthGet503Response) *NullableHealthGet503Response {
	return &NullableHealthGet503Response{value: val, isSet: true}
}

func (v NullableHealthGet503Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthGet503Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


