/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
)

// checks if the ApiV1ForecastsIdGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV1ForecastsIdGet200Response{}

// ApiV1ForecastsIdGet200Response struct for ApiV1ForecastsIdGet200Response
type ApiV1ForecastsIdGet200Response struct {
	// List of output files available for download. Populated once the job completes.
	Artifacts []ForecastArtifactMeta `json:"artifacts,omitempty"`
	JobId *string `json:"job_id,omitempty"`
	// Structured error from the pipeline for failed or canceled jobs; null otherwise. Common fields: `code` (string error code) and `detail` (human-readable explanation). Shape is defined by the pipeline and may vary. 
	PipelineError map[string]interface{} `json:"pipeline_error,omitempty"`
	// True once the job has reached a terminal state and the charge has been posted.
	Settled *bool `json:"settled,omitempty"`
	// Current lifecycle state of the job.
	Status *string `json:"status,omitempty"`
}

// NewApiV1ForecastsIdGet200Response instantiates a new ApiV1ForecastsIdGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1ForecastsIdGet200Response() *ApiV1ForecastsIdGet200Response {
	this := ApiV1ForecastsIdGet200Response{}
	return &this
}

// NewApiV1ForecastsIdGet200ResponseWithDefaults instantiates a new ApiV1ForecastsIdGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1ForecastsIdGet200ResponseWithDefaults() *ApiV1ForecastsIdGet200Response {
	this := ApiV1ForecastsIdGet200Response{}
	return &this
}

// GetArtifacts returns the Artifacts field value if set, zero value otherwise.
func (o *ApiV1ForecastsIdGet200Response) GetArtifacts() []ForecastArtifactMeta {
	if o == nil || IsNil(o.Artifacts) {
		var ret []ForecastArtifactMeta
		return ret
	}
	return o.Artifacts
}

// GetArtifactsOk returns a tuple with the Artifacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1ForecastsIdGet200Response) GetArtifactsOk() ([]ForecastArtifactMeta, bool) {
	if o == nil || IsNil(o.Artifacts) {
		return nil, false
	}
	return o.Artifacts, true
}

// HasArtifacts returns a boolean if a field has been set.
func (o *ApiV1ForecastsIdGet200Response) HasArtifacts() bool {
	if o != nil && !IsNil(o.Artifacts) {
		return true
	}

	return false
}

// SetArtifacts gets a reference to the given []ForecastArtifactMeta and assigns it to the Artifacts field.
func (o *ApiV1ForecastsIdGet200Response) SetArtifacts(v []ForecastArtifactMeta) {
	o.Artifacts = v
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *ApiV1ForecastsIdGet200Response) GetJobId() string {
	if o == nil || IsNil(o.JobId) {
		var ret string
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1ForecastsIdGet200Response) GetJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *ApiV1ForecastsIdGet200Response) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given string and assigns it to the JobId field.
func (o *ApiV1ForecastsIdGet200Response) SetJobId(v string) {
	o.JobId = &v
}

// GetPipelineError returns the PipelineError field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApiV1ForecastsIdGet200Response) GetPipelineError() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.PipelineError
}

// GetPipelineErrorOk returns a tuple with the PipelineError field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiV1ForecastsIdGet200Response) GetPipelineErrorOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.PipelineError) {
		return map[string]interface{}{}, false
	}
	return o.PipelineError, true
}

// HasPipelineError returns a boolean if a field has been set.
func (o *ApiV1ForecastsIdGet200Response) HasPipelineError() bool {
	if o != nil && !IsNil(o.PipelineError) {
		return true
	}

	return false
}

// SetPipelineError gets a reference to the given map[string]interface{} and assigns it to the PipelineError field.
func (o *ApiV1ForecastsIdGet200Response) SetPipelineError(v map[string]interface{}) {
	o.PipelineError = v
}

// GetSettled returns the Settled field value if set, zero value otherwise.
func (o *ApiV1ForecastsIdGet200Response) GetSettled() bool {
	if o == nil || IsNil(o.Settled) {
		var ret bool
		return ret
	}
	return *o.Settled
}

// GetSettledOk returns a tuple with the Settled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1ForecastsIdGet200Response) GetSettledOk() (*bool, bool) {
	if o == nil || IsNil(o.Settled) {
		return nil, false
	}
	return o.Settled, true
}

// HasSettled returns a boolean if a field has been set.
func (o *ApiV1ForecastsIdGet200Response) HasSettled() bool {
	if o != nil && !IsNil(o.Settled) {
		return true
	}

	return false
}

// SetSettled gets a reference to the given bool and assigns it to the Settled field.
func (o *ApiV1ForecastsIdGet200Response) SetSettled(v bool) {
	o.Settled = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ApiV1ForecastsIdGet200Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1ForecastsIdGet200Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ApiV1ForecastsIdGet200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ApiV1ForecastsIdGet200Response) SetStatus(v string) {
	o.Status = &v
}

func (o ApiV1ForecastsIdGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV1ForecastsIdGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Artifacts) {
		toSerialize["artifacts"] = o.Artifacts
	}
	if !IsNil(o.JobId) {
		toSerialize["job_id"] = o.JobId
	}
	if o.PipelineError != nil {
		toSerialize["pipeline_error"] = o.PipelineError
	}
	if !IsNil(o.Settled) {
		toSerialize["settled"] = o.Settled
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableApiV1ForecastsIdGet200Response struct {
	value *ApiV1ForecastsIdGet200Response
	isSet bool
}

func (v NullableApiV1ForecastsIdGet200Response) Get() *ApiV1ForecastsIdGet200Response {
	return v.value
}

func (v *NullableApiV1ForecastsIdGet200Response) Set(val *ApiV1ForecastsIdGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1ForecastsIdGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1ForecastsIdGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1ForecastsIdGet200Response(val *ApiV1ForecastsIdGet200Response) *NullableApiV1ForecastsIdGet200Response {
	return &NullableApiV1ForecastsIdGet200Response{value: val, isSet: true}
}

func (v NullableApiV1ForecastsIdGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1ForecastsIdGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


