/*
Sybilion API

The Sybilion API powers the Sybilion Developers Portal: forecasts, drivers, catalog, account and usage. Authenticate every request with `Authorization: Bearer <token>` using either an API key created in the Developers Portal or an Auth0 access token from your dashboard session. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sybilionapi

import (
	"encoding/json"
)

// checks if the ApiV1DriversPost200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV1DriversPost200ResponseData{}

// ApiV1DriversPost200ResponseData struct for ApiV1DriversPost200ResponseData
type ApiV1DriversPost200ResponseData struct {
	Drivers []DriverItemV1 `json:"drivers,omitempty"`
}

// NewApiV1DriversPost200ResponseData instantiates a new ApiV1DriversPost200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1DriversPost200ResponseData() *ApiV1DriversPost200ResponseData {
	this := ApiV1DriversPost200ResponseData{}
	return &this
}

// NewApiV1DriversPost200ResponseDataWithDefaults instantiates a new ApiV1DriversPost200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1DriversPost200ResponseDataWithDefaults() *ApiV1DriversPost200ResponseData {
	this := ApiV1DriversPost200ResponseData{}
	return &this
}

// GetDrivers returns the Drivers field value if set, zero value otherwise.
func (o *ApiV1DriversPost200ResponseData) GetDrivers() []DriverItemV1 {
	if o == nil || IsNil(o.Drivers) {
		var ret []DriverItemV1
		return ret
	}
	return o.Drivers
}

// GetDriversOk returns a tuple with the Drivers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1DriversPost200ResponseData) GetDriversOk() ([]DriverItemV1, bool) {
	if o == nil || IsNil(o.Drivers) {
		return nil, false
	}
	return o.Drivers, true
}

// HasDrivers returns a boolean if a field has been set.
func (o *ApiV1DriversPost200ResponseData) HasDrivers() bool {
	if o != nil && !IsNil(o.Drivers) {
		return true
	}

	return false
}

// SetDrivers gets a reference to the given []DriverItemV1 and assigns it to the Drivers field.
func (o *ApiV1DriversPost200ResponseData) SetDrivers(v []DriverItemV1) {
	o.Drivers = v
}

func (o ApiV1DriversPost200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV1DriversPost200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Drivers) {
		toSerialize["drivers"] = o.Drivers
	}
	return toSerialize, nil
}

type NullableApiV1DriversPost200ResponseData struct {
	value *ApiV1DriversPost200ResponseData
	isSet bool
}

func (v NullableApiV1DriversPost200ResponseData) Get() *ApiV1DriversPost200ResponseData {
	return v.value
}

func (v *NullableApiV1DriversPost200ResponseData) Set(val *ApiV1DriversPost200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1DriversPost200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1DriversPost200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1DriversPost200ResponseData(val *ApiV1DriversPost200ResponseData) *NullableApiV1DriversPost200ResponseData {
	return &NullableApiV1DriversPost200ResponseData{value: val, isSet: true}
}

func (v NullableApiV1DriversPost200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1DriversPost200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


